# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zcracks.ui'
#
# Created: Wed Oct 19 07:56:41 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Zui(object):
    def setupUi(self, Zui):
        Zui.setObjectName(_fromUtf8("Zui"))
        Zui.resize(709, 540)
        Zui.setMinimumSize(QtCore.QSize(709, 540))
        Zui.setMaximumSize(QtCore.QSize(709, 540))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        Zui.setPalette(palette)
        Zui.setTitle(_fromUtf8(""))
        self.horizontalLayoutWidget = QtGui.QWidget(Zui)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(3, 497, 301, 37))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btReset = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btReset.setMinimumSize(QtCore.QSize(85, 35))
        self.btReset.setMaximumSize(QtCore.QSize(85, 35))
        self.btReset.setObjectName(_fromUtf8("btReset"))
        self.horizontalLayout.addWidget(self.btReset)
        self.btSave = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btSave.setMinimumSize(QtCore.QSize(85, 35))
        self.btSave.setMaximumSize(QtCore.QSize(85, 35))
        self.btSave.setObjectName(_fromUtf8("btSave"))
        self.horizontalLayout.addWidget(self.btSave)
        self.btLoad = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btLoad.setMinimumSize(QtCore.QSize(85, 35))
        self.btLoad.setMaximumSize(QtCore.QSize(85, 35))
        self.btLoad.setObjectName(_fromUtf8("btLoad"))
        self.horizontalLayout.addWidget(self.btLoad)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Zui)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(344, 490, 360, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btCancel = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btCancel.setMinimumSize(QtCore.QSize(100, 35))
        self.btCancel.setMaximumSize(QtCore.QSize(100, 35))
        self.btCancel.setObjectName(_fromUtf8("btCancel"))
        self.horizontalLayout_2.addWidget(self.btCancel)
        self.btApply = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btApply.setMinimumSize(QtCore.QSize(100, 35))
        self.btApply.setMaximumSize(QtCore.QSize(100, 35))
        self.btApply.setObjectName(_fromUtf8("btApply"))
        self.horizontalLayout_2.addWidget(self.btApply)
        self.btApplyClose = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btApplyClose.setMinimumSize(QtCore.QSize(130, 35))
        self.btApplyClose.setMaximumSize(QtCore.QSize(130, 35))
        self.btApplyClose.setObjectName(_fromUtf8("btApplyClose"))
        self.horizontalLayout_2.addWidget(self.btApplyClose)
        self.frame = QtGui.QFrame(Zui)
        self.frame.setGeometry(QtCore.QRect(3, 6, 309, 255))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-2, 21, 311, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtCrackedName = QtGui.QLabel(self.gridLayoutWidget)
        self.txtCrackedName.setMinimumSize(QtCore.QSize(112, 0))
        self.txtCrackedName.setMaximumSize(QtCore.QSize(76, 16777215))
        self.txtCrackedName.setStatusTip(_fromUtf8(""))
        self.txtCrackedName.setWhatsThis(_fromUtf8(""))
        self.txtCrackedName.setAccessibleName(_fromUtf8(""))
        self.txtCrackedName.setAccessibleDescription(_fromUtf8(""))
        self.txtCrackedName.setObjectName(_fromUtf8("txtCrackedName"))
        self.gridLayout.addWidget(self.txtCrackedName, 0, 0, 1, 1)
        self.valCrackedName = QtGui.QLineEdit(self.gridLayoutWidget)
        self.valCrackedName.setMinimumSize(QtCore.QSize(118, 0))
        self.valCrackedName.setAutoFillBackground(True)
        self.valCrackedName.setObjectName(_fromUtf8("valCrackedName"))
        self.gridLayout.addWidget(self.valCrackedName, 0, 1, 1, 1)
        self.txtSaneName = QtGui.QLabel(self.gridLayoutWidget)
        self.txtSaneName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtSaneName.setObjectName(_fromUtf8("txtSaneName"))
        self.gridLayout.addWidget(self.txtSaneName, 1, 0, 1, 1)
        self.valSaneName = QtGui.QLineEdit(self.gridLayoutWidget)
        self.valSaneName.setToolTip(_fromUtf8("file adress (ex: /home/A123456/cuve.med)"))
        self.valSaneName.setAutoFillBackground(True)
        self.valSaneName.setInputMask(_fromUtf8(""))
        self.valSaneName.setText(_fromUtf8(""))
        self.valSaneName.setObjectName(_fromUtf8("valSaneName"))
        self.gridLayout.addWidget(self.valSaneName, 1, 1, 1, 1)
        self.btLoadCracked = QtGui.QPushButton(self.gridLayoutWidget)
        self.btLoadCracked.setMinimumSize(QtCore.QSize(28, 28))
        self.btLoadCracked.setMaximumSize(QtCore.QSize(28, 28))
        self.btLoadCracked.setObjectName(_fromUtf8("btLoadCracked"))
        self.gridLayout.addWidget(self.btLoadCracked, 0, 2, 1, 1)
        self.btLoadSane = QtGui.QPushButton(self.gridLayoutWidget)
        self.btLoadSane.setMinimumSize(QtCore.QSize(28, 28))
        self.btLoadSane.setMaximumSize(QtCore.QSize(28, 28))
        self.btLoadSane.setObjectName(_fromUtf8("btLoadSane"))
        self.gridLayout.addWidget(self.btLoadSane, 1, 2, 1, 1)
        self.cracked_name_2 = QtGui.QLabel(self.frame)
        self.cracked_name_2.setGeometry(QtCore.QRect(0, 0, 311, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.cracked_name_2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cracked_name_2.setFont(font)
        self.cracked_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cracked_name_2.setObjectName(_fromUtf8("cracked_name_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(-2, 102, 311, 161))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.txtMaxSize = QtGui.QLabel(self.gridLayoutWidget_3)
        self.txtMaxSize.setObjectName(_fromUtf8("txtMaxSize"))
        self.gridLayout_3.addWidget(self.txtMaxSize, 1, 0, 1, 1)
        self.txtExtractLength = QtGui.QLabel(self.gridLayoutWidget_3)
        self.txtExtractLength.setObjectName(_fromUtf8("txtExtractLength"))
        self.gridLayout_3.addWidget(self.txtExtractLength, 2, 0, 1, 1)
        self.valMinSize = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.valMinSize.setAutoFillBackground(True)
        self.valMinSize.setObjectName(_fromUtf8("valMinSize"))
        self.gridLayout_3.addWidget(self.valMinSize, 0, 1, 1, 1)
        self.valMaxSize = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.valMaxSize.setAutoFillBackground(True)
        self.valMaxSize.setObjectName(_fromUtf8("valMaxSize"))
        self.gridLayout_3.addWidget(self.valMaxSize, 1, 1, 1, 1)
        self.valExtractLength = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.valExtractLength.setAutoFillBackground(True)
        self.valExtractLength.setObjectName(_fromUtf8("valExtractLength"))
        self.gridLayout_3.addWidget(self.valExtractLength, 2, 1, 1, 1)
        self.CBQuad = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.CBQuad.setObjectName(_fromUtf8("CBQuad"))
        self.gridLayout_3.addWidget(self.CBQuad, 3, 0, 1, 1)
        self.CBBarsoum = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.CBBarsoum.setEnabled(False)
        self.CBBarsoum.setObjectName(_fromUtf8("CBBarsoum"))
        self.gridLayout_3.addWidget(self.CBBarsoum, 3, 1, 1, 1)
        self.txtMinSize = QtGui.QLabel(self.gridLayoutWidget_3)
        self.txtMinSize.setObjectName(_fromUtf8("txtMinSize"))
        self.gridLayout_3.addWidget(self.txtMinSize, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(Zui)
        self.frame_2.setGeometry(QtCore.QRect(2, 265, 309, 226))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.labelCrackedName = QtGui.QLabel(self.frame_2)
        self.labelCrackedName.setGeometry(QtCore.QRect(-1, 0, 311, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCrackedName.setFont(font)
        self.labelCrackedName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCrackedName.setObjectName(_fromUtf8("labelCrackedName"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 14, 311, 220))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtGrVol = QtGui.QLabel(self.gridLayoutWidget_2)
        self.txtGrVol.setObjectName(_fromUtf8("txtGrVol"))
        self.gridLayout_2.addWidget(self.txtGrVol, 0, 0, 1, 1)
        self.valGrVol = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.valGrVol.setAutoFillBackground(True)
        self.valGrVol.setObjectName(_fromUtf8("valGrVol"))
        self.gridLayout_2.addWidget(self.valGrVol, 0, 1, 1, 1)
        self.txtGrFace = QtGui.QLabel(self.gridLayoutWidget_2)
        self.txtGrFace.setToolTip(_fromUtf8("Groups of faces to keep"))
        self.txtGrFace.setObjectName(_fromUtf8("txtGrFace"))
        self.gridLayout_2.addWidget(self.txtGrFace, 1, 0, 1, 1)
        self.valGrFace = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.valGrFace.setToolTip(_fromUtf8("groups separated by a space (ex: Gr1 Gr2 Gr3)"))
        self.valGrFace.setAutoFillBackground(True)
        self.valGrFace.setInputMask(_fromUtf8(""))
        self.valGrFace.setText(_fromUtf8(""))
        self.valGrFace.setObjectName(_fromUtf8("valGrFace"))
        self.gridLayout_2.addWidget(self.valGrFace, 1, 1, 1, 1)
        self.txtGrEdge = QtGui.QLabel(self.gridLayoutWidget_2)
        self.txtGrEdge.setObjectName(_fromUtf8("txtGrEdge"))
        self.gridLayout_2.addWidget(self.txtGrEdge, 2, 0, 1, 1)
        self.valGrEdge = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.valGrEdge.setAutoFillBackground(True)
        self.valGrEdge.setObjectName(_fromUtf8("valGrEdge"))
        self.gridLayout_2.addWidget(self.valGrEdge, 2, 1, 1, 1)
        self.txtGrNode = QtGui.QLabel(self.gridLayoutWidget_2)
        self.txtGrNode.setObjectName(_fromUtf8("txtGrNode"))
        self.gridLayout_2.addWidget(self.txtGrNode, 3, 0, 1, 1)
        self.valGrNode = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.valGrNode.setAutoFillBackground(True)
        self.valGrNode.setObjectName(_fromUtf8("valGrNode"))
        self.gridLayout_2.addWidget(self.valGrNode, 3, 1, 1, 1)
        self.btGrVol = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btGrVol.setMaximumSize(QtCore.QSize(40, 28))
        self.btGrVol.setObjectName(_fromUtf8("btGrVol"))
        self.gridLayout_2.addWidget(self.btGrVol, 0, 2, 1, 1)
        self.btGrFace = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btGrFace.setMaximumSize(QtCore.QSize(40, 28))
        self.btGrFace.setObjectName(_fromUtf8("btGrFace"))
        self.gridLayout_2.addWidget(self.btGrFace, 1, 2, 1, 1)
        self.btGrEdge = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btGrEdge.setMaximumSize(QtCore.QSize(40, 28))
        self.btGrEdge.setObjectName(_fromUtf8("btGrEdge"))
        self.gridLayout_2.addWidget(self.btGrEdge, 2, 2, 1, 1)
        self.btGrNode = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btGrNode.setMaximumSize(QtCore.QSize(40, 28))
        self.btGrNode.setObjectName(_fromUtf8("btGrNode"))
        self.gridLayout_2.addWidget(self.btGrNode, 3, 2, 1, 1)
        self.btGrAll = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btGrAll.setMaximumSize(QtCore.QSize(80, 28))
        self.btGrAll.setObjectName(_fromUtf8("btGrAll"))
        self.gridLayout_2.addWidget(self.btGrAll, 4, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(Zui)
        self.frame_3.setGeometry(QtCore.QRect(317, 6, 388, 333))
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.tabWidget = QtGui.QTabWidget(self.frame_3)
        self.tabWidget.setGeometry(QtCore.QRect(4, 23, 378, 306))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 270))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 331))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ongletEllipse = QtGui.QWidget()
        self.ongletEllipse.setObjectName(_fromUtf8("ongletEllipse"))
        self.tabEllipse = QtGui.QTableWidget(self.ongletEllipse)
        self.tabEllipse.setGeometry(QtCore.QRect(0, 0, 375, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabEllipse.sizePolicy().hasHeightForWidth())
        self.tabEllipse.setSizePolicy(sizePolicy)
        self.tabEllipse.setMaximumSize(QtCore.QSize(16777215, 301))
        self.tabEllipse.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.tabEllipse.setFont(font)
        self.tabEllipse.setMouseTracking(False)
        self.tabEllipse.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabEllipse.setAutoFillBackground(False)
        self.tabEllipse.setObjectName(_fromUtf8("tabEllipse"))
        self.tabEllipse.setColumnCount(1)
        self.tabEllipse.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tabEllipse.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabEllipse.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabEllipse.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tabEllipse.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabEllipse.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabEllipse.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabEllipse.setItem(5, 0, item)
        self.infoEllipse = QtGui.QLabel(self.ongletEllipse)
        self.infoEllipse.setGeometry(QtCore.QRect(330, 0, 40, 25))
        self.infoEllipse.setAlignment(QtCore.Qt.AlignCenter)
        self.infoEllipse.setObjectName(_fromUtf8("infoEllipse"))
        self.tabWidget.addTab(self.ongletEllipse, _fromUtf8(""))
        self.ongletRectangle = QtGui.QWidget()
        self.ongletRectangle.setObjectName(_fromUtf8("ongletRectangle"))
        self.tabRectangle = QtGui.QTableWidget(self.ongletRectangle)
        self.tabRectangle.setGeometry(QtCore.QRect(0, 0, 375, 271))
        self.tabRectangle.setMaximumSize(QtCore.QSize(16777215, 301))
        self.tabRectangle.setObjectName(_fromUtf8("tabRectangle"))
        self.tabRectangle.setColumnCount(1)
        self.tabRectangle.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabRectangle.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabRectangle.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabRectangle.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabRectangle.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabRectangle.setItem(6, 0, item)
        self.infoRectangle = QtGui.QLabel(self.ongletRectangle)
        self.infoRectangle.setGeometry(QtCore.QRect(330, 0, 40, 25))
        self.infoRectangle.setAlignment(QtCore.Qt.AlignCenter)
        self.infoRectangle.setObjectName(_fromUtf8("infoRectangle"))
        self.tabWidget.addTab(self.ongletRectangle, _fromUtf8(""))
        self.ongletSphere = QtGui.QWidget()
        self.ongletSphere.setObjectName(_fromUtf8("ongletSphere"))
        self.tabSphere = QtGui.QTableWidget(self.ongletSphere)
        self.tabSphere.setGeometry(QtCore.QRect(0, 0, 375, 272))
        self.tabSphere.setMaximumSize(QtCore.QSize(16777215, 301))
        self.tabSphere.setObjectName(_fromUtf8("tabSphere"))
        self.tabSphere.setColumnCount(1)
        self.tabSphere.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabSphere.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabSphere.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabSphere.setHorizontalHeaderItem(0, item)
        self.infoSphere = QtGui.QLabel(self.ongletSphere)
        self.infoSphere.setGeometry(QtCore.QRect(330, 0, 40, 25))
        self.infoSphere.setAlignment(QtCore.Qt.AlignCenter)
        self.infoSphere.setObjectName(_fromUtf8("infoSphere"))
        self.tabWidget.addTab(self.ongletSphere, _fromUtf8(""))
        self.ongletPerso = QtGui.QWidget()
        self.ongletPerso.setObjectName(_fromUtf8("ongletPerso"))
        self.tabPerso = QtGui.QTableWidget(self.ongletPerso)
        self.tabPerso.setGeometry(QtCore.QRect(0, 0, 375, 271))
        self.tabPerso.setMaximumSize(QtCore.QSize(16777215, 301))
        self.tabPerso.setObjectName(_fromUtf8("tabPerso"))
        self.tabPerso.setColumnCount(1)
        self.tabPerso.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabPerso.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tabPerso.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPerso.setItem(0, 0, item)
        self.infoCustom = QtGui.QLabel(self.ongletPerso)
        self.infoCustom.setGeometry(QtCore.QRect(330, 0, 40, 25))
        self.infoCustom.setAlignment(QtCore.Qt.AlignCenter)
        self.infoCustom.setObjectName(_fromUtf8("infoCustom"))
        self.tabWidget.addTab(self.ongletPerso, _fromUtf8(""))
        self.labelCrackName = QtGui.QLabel(self.frame_3)
        self.labelCrackName.setGeometry(QtCore.QRect(0, 0, 381, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCrackName.setFont(font)
        self.labelCrackName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCrackName.setObjectName(_fromUtf8("labelCrackName"))
        self.frame_4 = QtGui.QFrame(Zui)
        self.frame_4.setEnabled(True)
        self.frame_4.setGeometry(QtCore.QRect(317, 344, 388, 147))
        self.frame_4.setFrameShape(QtGui.QFrame.Panel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.CBAdvanced = QtGui.QCheckBox(self.frame_4)
        self.CBAdvanced.setGeometry(QtCore.QRect(6, 2, 171, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBAdvanced.setFont(font)
        self.CBAdvanced.setObjectName(_fromUtf8("CBAdvanced"))
        self.widget = QtGui.QWidget(self.frame_4)
        self.widget.setGeometry(QtCore.QRect(0, 24, 427, 106))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayoutWidget_9 = QtGui.QWidget(self.widget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(1, 35, 381, 40))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.btVisu = QtGui.QPushButton(self.gridLayoutWidget_9)
        self.btVisu.setMinimumSize(QtCore.QSize(85, 28))
        self.btVisu.setMaximumSize(QtCore.QSize(85, 28))
        self.btVisu.setObjectName(_fromUtf8("btVisu"))
        self.gridLayout_9.addWidget(self.btVisu, 0, 0, 1, 1)
        self.txtSurfopt = QtGui.QLabel(self.gridLayoutWidget_9)
        self.txtSurfopt.setMinimumSize(QtCore.QSize(67, 28))
        self.txtSurfopt.setMaximumSize(QtCore.QSize(16777215, 28))
        self.txtSurfopt.setObjectName(_fromUtf8("txtSurfopt"))
        self.gridLayout_9.addWidget(self.txtSurfopt, 0, 1, 1, 1)
        self.valSurfopt = QtGui.QLineEdit(self.gridLayoutWidget_9)
        self.valSurfopt.setMinimumSize(QtCore.QSize(0, 28))
        self.valSurfopt.setMaximumSize(QtCore.QSize(16777215, 28))
        self.valSurfopt.setAutoFillBackground(True)
        self.valSurfopt.setText(_fromUtf8(""))
        self.valSurfopt.setObjectName(_fromUtf8("valSurfopt"))
        self.gridLayout_9.addWidget(self.valSurfopt, 0, 2, 1, 1)
        self.CBIs2D = QtGui.QCheckBox(self.widget)
        self.CBIs2D.setGeometry(QtCore.QRect(0, 80, 81, 26))
        self.CBIs2D.setObjectName(_fromUtf8("CBIs2D"))
        self.CBRefine = QtGui.QCheckBox(self.widget)
        self.CBRefine.setGeometry(QtCore.QRect(90, 80, 92, 26))
        self.CBRefine.setObjectName(_fromUtf8("CBRefine"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.widget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(2, 6, 381, 30))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txtGradation = QtGui.QLabel(self.gridLayoutWidget_8)
        self.txtGradation.setMinimumSize(QtCore.QSize(0, 28))
        self.txtGradation.setObjectName(_fromUtf8("txtGradation"))
        self.gridLayout_8.addWidget(self.txtGradation, 0, 0, 1, 1)
        self.valGradation = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.valGradation.setMinimumSize(QtCore.QSize(40, 28))
        self.valGradation.setAutoFillBackground(True)
        self.valGradation.setObjectName(_fromUtf8("valGradation"))
        self.gridLayout_8.addWidget(self.valGradation, 0, 1, 1, 1)
        self.txtLayers = QtGui.QLabel(self.gridLayoutWidget_8)
        self.txtLayers.setMinimumSize(QtCore.QSize(50, 28))
        self.txtLayers.setObjectName(_fromUtf8("txtLayers"))
        self.gridLayout_8.addWidget(self.txtLayers, 0, 2, 1, 1)
        self.txtIterations = QtGui.QLabel(self.gridLayoutWidget_8)
        self.txtIterations.setMinimumSize(QtCore.QSize(69, 0))
        self.txtIterations.setMaximumSize(QtCore.QSize(16777215, 28))
        self.txtIterations.setObjectName(_fromUtf8("txtIterations"))
        self.gridLayout_8.addWidget(self.txtIterations, 0, 4, 1, 1)
        self.valLayers = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.valLayers.setMinimumSize(QtCore.QSize(30, 28))
        self.valLayers.setMaximumSize(QtCore.QSize(35, 16777215))
        self.valLayers.setAutoFillBackground(True)
        self.valLayers.setObjectName(_fromUtf8("valLayers"))
        self.gridLayout_8.addWidget(self.valLayers, 0, 3, 1, 1)
        self.valIterations = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.valIterations.setMinimumSize(QtCore.QSize(30, 28))
        self.valIterations.setMaximumSize(QtCore.QSize(30, 28))
        self.valIterations.setAutoFillBackground(True)
        self.valIterations.setObjectName(_fromUtf8("valIterations"))
        self.gridLayout_8.addWidget(self.valIterations, 0, 5, 1, 1)

        self.retranslateUi(Zui)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Zui)

    def retranslateUi(self, Zui):
        Zui.setWindowTitle(_translate("Zui", "Zcracks interface - version dev", None))
        self.btReset.setToolTip(_translate("Zui", "Clear all paramters", None))
        self.btReset.setText(_translate("Zui", "Reset", None))
        self.btSave.setToolTip(_translate("Zui", "Save parameters in a file", None))
        self.btSave.setText(_translate("Zui", "Save", None))
        self.btLoad.setToolTip(_translate("Zui", "Load all parameters from a file", None))
        self.btLoad.setText(_translate("Zui", "Load", None))
        self.btCancel.setToolTip(_translate("Zui", "Exit Zcracks", None))
        self.btCancel.setText(_translate("Zui", "Cancel", None))
        self.btApply.setToolTip(_translate("Zui", "Launch crack insertion", None))
        self.btApply.setText(_translate("Zui", "Apply", None))
        self.btApplyClose.setToolTip(_translate("Zui", "Launch crack insertion and quit", None))
        self.btApplyClose.setText(_translate("Zui", "Apply and close", None))
        self.txtCrackedName.setToolTip(_translate("Zui", "Name of the resulting cracked mesh", None))
        self.txtCrackedName.setText(_translate("Zui", "Cracked name", None))
        self.valCrackedName.setToolTip(_translate("Zui", "file adress (ex: /home/A123456/cracked.med)", None))
        self.txtSaneName.setToolTip(_translate("Zui", "Name of the sane mesh", None))
        self.txtSaneName.setText(_translate("Zui", "Sane mesh", None))
        self.btLoadCracked.setText(_translate("Zui", "...", None))
        self.btLoadSane.setText(_translate("Zui", "...", None))
        self.cracked_name_2.setToolTip(_translate("Zui", "General parameters", None))
        self.cracked_name_2.setText(_translate("Zui", "Mesh parameters", None))
        self.txtMaxSize.setToolTip(_translate("Zui", "Maximum mesh size", None))
        self.txtMaxSize.setText(_translate("Zui", "Maximum size", None))
        self.txtExtractLength.setToolTip(_translate("Zui", "Extraction length (optionnal)", None))
        self.txtExtractLength.setText(_translate("Zui", "Extraction length", None))
        self.valMinSize.setToolTip(_translate("Zui", "float (ex: 1.E-04)", None))
        self.valMaxSize.setToolTip(_translate("Zui", "float (ex: 1.E-03)", None))
        self.valExtractLength.setToolTip(_translate("Zui", "float (ex: 1.E-04)", None))
        self.CBQuad.setToolTip(_translate("Zui", "Quadratic cracked mesh", None))
        self.CBQuad.setText(_translate("Zui", "Quadratic", None))
        self.CBBarsoum.setToolTip(_translate("Zui", "Use Barsoum (quarter nodes) elements at crack front", None))
        self.CBBarsoum.setText(_translate("Zui", "Barsoum", None))
        self.txtMinSize.setToolTip(_translate("Zui", "Minimum mesh size", None))
        self.txtMinSize.setText(_translate("Zui", "Minimum size", None))
        self.labelCrackedName.setToolTip(_translate("Zui", "Groups to save (limit list to vital groups)", None))
        self.labelCrackedName.setText(_translate("Zui", "Groups", None))
        self.txtGrVol.setToolTip(_translate("Zui", "Groups of volumes to keep", None))
        self.txtGrVol.setText(_translate("Zui", "Volumes", None))
        self.valGrVol.setToolTip(_translate("Zui", "groups separated by a space (ex: Gr1 Gr2 Gr3)", None))
        self.txtGrFace.setText(_translate("Zui", "Faces", None))
        self.txtGrEdge.setToolTip(_translate("Zui", "Groups of edges to keep", None))
        self.txtGrEdge.setText(_translate("Zui", "Edges", None))
        self.valGrEdge.setToolTip(_translate("Zui", "groups separated by a space (ex: Gr1 Gr2 Gr3)", None))
        self.txtGrNode.setToolTip(_translate("Zui", "Groups of nodes to keep", None))
        self.txtGrNode.setText(_translate("Zui", "Nodes", None))
        self.valGrNode.setToolTip(_translate("Zui", "groups separated by a space (ex: Gr1 Gr2 Gr3)", None))
        self.btGrVol.setText(_translate("Zui", "Load", None))
        self.btGrFace.setText(_translate("Zui", "Load", None))
        self.btGrEdge.setText(_translate("Zui", "Load", None))
        self.btGrNode.setText(_translate("Zui", "Load", None))
        self.btGrAll.setText(_translate("Zui", "Load all", None))
        item = self.tabEllipse.verticalHeaderItem(0)
        item.setText(_translate("Zui", "Centre", None))
        item = self.tabEllipse.verticalHeaderItem(1)
        item.setText(_translate("Zui", "Normale", None))
        item = self.tabEllipse.verticalHeaderItem(2)
        item.setText(_translate("Zui", "Rayon", None))
        item = self.tabEllipse.verticalHeaderItem(3)
        item.setText(_translate("Zui", "Direction", None))
        item = self.tabEllipse.verticalHeaderItem(4)
        item.setText(_translate("Zui", "Rayon 2", None))
        item = self.tabEllipse.verticalHeaderItem(5)
        item.setText(_translate("Zui", "Angle", None))
        item = self.tabEllipse.verticalHeaderItem(6)
        item.setText(_translate("Zui", "Rayon entaille", None))
        item = self.tabEllipse.verticalHeaderItem(7)
        item.setText(_translate("Zui", "Extension", None))
        item = self.tabEllipse.horizontalHeaderItem(0)
        item.setText(_translate("Zui", "Valeur", None))
        __sortingEnabled = self.tabEllipse.isSortingEnabled()
        self.tabEllipse.setSortingEnabled(False)
        self.tabEllipse.setSortingEnabled(__sortingEnabled)
        self.infoEllipse.setToolTip(_translate("Zui", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Fissure de forme elliptique :</span></p><p><img src=\":/newPrefix/images/schema_ellipse.png\"/><br/></p><p><span style=\" font-weight:600; text-decoration: underline;\">Centre</span> : Coordonnées du centre de l\'ellipse (ex: 0 0 1)</p><p><span style=\" font-weight:600; text-decoration: underline;\">Normale</span> : Coordonnées du vecteur normal à l\'ellipse (ex: 1 0 0)</p><p><span style=\" font-weight:600; text-decoration: underline;\">Rayon</span> : Rayon de l\'ellipse le long du vecteur direction (ex: 1.0e1)</p><p><span style=\" text-decoration: underline;\">Direction</span> : Coordonnées du vecteur direction de l\'ellipse (ex: 0 1 0). Nécessaire pour une ellipse</p><p><span style=\" text-decoration: underline;\">Rayon 2</span> : Rayon de l\'ellipse le long du vecteur orthogonal à normale et direction (ex: 1.0e1). Si vide égal à Rayon</p><p><span style=\" text-decoration: underline;\">Angle</span> : Angle en degrés pour une ellipse tronquée (ex: 180.). Si vide, l\'ellipse n\'est pas tronquée</p><p><span style=\" text-decoration: underline;\">Rayon entaille</span> : Rayon du fond d\'entaille. (ex: 1.0e1). Si vide, la fissure est plane sans entaille</p><p><span style=\" text-decoration: underline;\">Extension</span> : Longueur d\'extension de l\'ellipse tronquée dans le long de la direction opposée à Direction (ex: 1.0)</p><p><span style=\" font-weight:600; font-style:italic;\">Gras : Informations obligatoires</span></p></body></html>", None))
        self.infoEllipse.setText(_translate("Zui", "?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletEllipse), _translate("Zui", "Ellipse", None))
        item = self.tabRectangle.verticalHeaderItem(0)
        item.setText(_translate("Zui", "Centre", None))
        item = self.tabRectangle.verticalHeaderItem(1)
        item.setText(_translate("Zui", "Normale", None))
        item = self.tabRectangle.verticalHeaderItem(2)
        item.setText(_translate("Zui", "Longueur", None))
        item = self.tabRectangle.verticalHeaderItem(3)
        item.setText(_translate("Zui", "Direction", None))
        item = self.tabRectangle.verticalHeaderItem(4)
        item.setText(_translate("Zui", "Largeur", None))
        item = self.tabRectangle.verticalHeaderItem(5)
        item.setText(_translate("Zui", "Rayon", None))
        item = self.tabRectangle.verticalHeaderItem(6)
        item.setText(_translate("Zui", "Angle", None))
        item = self.tabRectangle.verticalHeaderItem(7)
        item.setText(_translate("Zui", "Rayon entaille", None))
        item = self.tabRectangle.horizontalHeaderItem(0)
        item.setText(_translate("Zui", "Valeur", None))
        __sortingEnabled = self.tabRectangle.isSortingEnabled()
        self.tabRectangle.setSortingEnabled(False)
        self.tabRectangle.setSortingEnabled(__sortingEnabled)
        self.infoRectangle.setToolTip(_translate("Zui", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Fissure de forme rectangulaire :</span></p><p><img src=\":/newPrefix/images/schema_rectangle.png\"/><br/></p><p><span style=\" font-weight:600; text-decoration: underline;\">Centre</span> : Coordonnées du centre du rectangle (ex: 0 0 1)</p><p><span style=\" font-weight:600; text-decoration: underline;\">Normale</span> : Coordonnées du vecteur normal au rectangle (ex: 1 0 0)</p><p><span style=\" font-weight:600; text-decoration: underline;\">Longueur</span> : Demie longueur du rectangle le long du vecteur direction (ex: 1.0e1)</p><p><span style=\" font-weight:600; text-decoration: underline;\">Direction</span> : Coordonnées du vecteur direction du rectangle (ex: 0 1 0)</p><p><span style=\" text-decoration: underline;\">Largeur</span> : Demie largeur du rectangle le long du vecteur orthogonal à normale et direction (ex: 1.0e1). Si vide, égal à Longueur</p><p><span style=\" text-decoration: underline;\">Rayon </span>: Rayon du congé aux angles du rectangle (ex: 1.0e1). Si vide, pas de congé</p><p><span style=\" text-decoration: underline;\">Angle</span> : Angle en degrés pour un rectangle tronqué (ex: 180.). Si vide, le rectangle n\'est pas tronquée</p><p><span style=\" text-decoration: underline;\">Rayon entaille</span> : Rayon du fond d\'entaille. (ex: 1.0e1). Si vide, la fissure est plane sans entaille</p><p><span style=\" font-weight:600; font-style:italic;\">Gras : Informations obligatoires</span></p></body></html>", None))
        self.infoRectangle.setText(_translate("Zui", "?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletRectangle), _translate("Zui", "Rectangle", None))
        item = self.tabSphere.verticalHeaderItem(0)
        item.setText(_translate("Zui", "Centre", None))
        item = self.tabSphere.verticalHeaderItem(1)
        item.setText(_translate("Zui", "Rayon", None))
        item = self.tabSphere.horizontalHeaderItem(0)
        item.setText(_translate("Zui", "Valeur", None))
        self.infoSphere.setToolTip(_translate("Zui", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Fissure de forme spherique :</span></p><p><img src=\":/newPrefix/images/schema_shpere.png\"/><br/></p><p><span style=\" font-weight:600; text-decoration: underline;\">Centre</span> : Coordonnées du centre de la sphere (ex: 0 0 1)</p><p><span style=\" font-weight:600; text-decoration: underline;\">Rayon</span> : Rayon de la sphere (ex: 1.0e1)</p><p><span style=\" font-weight:600; font-style:italic;\">Gras : Informations obligatoires</span></p></body></html>", None))
        self.infoSphere.setText(_translate("Zui", "?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletSphere), _translate("Zui", "Sphere", None))
        item = self.tabPerso.verticalHeaderItem(0)
        item.setText(_translate("Zui", "med file", None))
        item = self.tabPerso.horizontalHeaderItem(0)
        item.setText(_translate("Zui", "File", None))
        __sortingEnabled = self.tabPerso.isSortingEnabled()
        self.tabPerso.setSortingEnabled(False)
        self.tabPerso.setSortingEnabled(__sortingEnabled)
        self.infoCustom.setToolTip(_translate("Zui", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Fissure de forme personnalisée :</span></p><p><span style=\" font-weight:600; text-decoration: underline;\">Med file</span> : Adresse du maillage décrivant la fissure (ex: $HOME/PROJETX/fissure3.med)</p><p><span style=\" font-style:italic;\">Le maillage de la fissure doit être une surface composée de tétrahèdres linéaires uniquement.</span></p><p><span style=\" font-weight:600; font-style:italic;\">Gras : Informations obligatoires</span></p></body></html>", None))
        self.infoCustom.setText(_translate("Zui", "?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletPerso), _translate("Zui", "Custom", None))
        self.labelCrackName.setToolTip(_translate("Zui", "Crack automatic generation", None))
        self.labelCrackName.setText(_translate("Zui", "Crack", None))
        self.CBAdvanced.setToolTip(_translate("Zui", "Advanced options (Use with caution)", None))
        self.CBAdvanced.setText(_translate("Zui", "Advanced options", None))
        self.btVisu.setToolTip(_translate("Zui", "Load all parameters from a file", None))
        self.btVisu.setText(_translate("Zui", "Quick View", None))
        self.txtSurfopt.setToolTip(_translate("Zui", "SURFOPT options", None))
        self.txtSurfopt.setText(_translate("Zui", "SURFOPT", None))
        self.valSurfopt.setToolTip(_translate("Zui", "string", None))
        self.CBIs2D.setToolTip(_translate("Zui", "Check if sane mesh is a surface", None))
        self.CBIs2D.setText(_translate("Zui", "2D case", None))
        self.CBRefine.setToolTip(_translate("Zui", "Check to refine sane mesh before crack insertion", None))
        self.CBRefine.setText(_translate("Zui", "Pre refine", None))
        self.txtGradation.setToolTip(_translate("Zui", "Mesh increase parameter", None))
        self.txtGradation.setText(_translate("Zui", "Gradation", None))
        self.valGradation.setToolTip(_translate("Zui", "float (ex: 1.3)", None))
        self.valGradation.setText(_translate("Zui", "1.3", None))
        self.txtLayers.setToolTip(_translate("Zui", "Constant size layers number", None))
        self.txtLayers.setText(_translate("Zui", "Layers", None))
        self.txtIterations.setToolTip(_translate("Zui", "Remeshing iterations number", None))
        self.txtIterations.setText(_translate("Zui", "Iterations", None))
        self.valLayers.setToolTip(_translate("Zui", "integer (ex: 5)", None))
        self.valLayers.setText(_translate("Zui", "5", None))
        self.valIterations.setToolTip(_translate("Zui", "integer (ex: 2)", None))
        self.valIterations.setText(_translate("Zui", "2", None))

import images_rc
