dicoDimENtite= { 'Entity_Node':0,
'Entity_0D':0,
'Entity_Ball':0,
'Entity_Edge':0,
'Entity_Quad_Edge':0,
'Entity_Triangle':1,
'Entity_Quad_Triangle':1,
'Entity_BiQuad_Triangle':1,
'Entity_Quadrangle':1,
'Entity_Quad_Quadrangle':1,
'Entity_BiQuad_Quadrangle':1,
'Entity_Polygon':1,
'Entity_Quad_Polygon':1,
'Entity_Tetra':1,
'Entity_Quad_Tetra':1,
'Entity_Hexa':1,
'Entity_Quad_Hexa':1,
'Entity_TriQuad_Hexa':1,
'Entity_Pyramid ':1,
'Entity_Quad_Pyramid':1,
'Entity_Penta ':1,
'Entity_Quad_Penta':1,
'Entity_Hexagonal_Prism':1,
'Entity_Polyhedra':1,
'Entity_Quad_Polyhedra':1,
}
