<!DOCTYPE TS>
<TS version="1.1" >
    <context>
        <name>@default</name>
        <message>
            <source>ICON_DLG_ARITHMETIC_1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_AUTOMATIC_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_DEFLECTION1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GEOMETRIC_1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LAYER_DISTRIBUTION</source>
            <translation>mesh_hypo_layer_distribution.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LOCAL_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MAX_ELEMENT_AREA</source>
            <translation>mesh_hypo_area.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MAX_ELEMENT_VOLUME</source>
            <translation>mesh_hypo_volume.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NB_SEGMENTS</source>
            <translation>mesh_hypo_segment.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NUMBER_OF_LAYERS</source>
            <translation>mesh_hypo_layer_distribution.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_SOURCE_1D</source>
            <translation>mesh_hypo_source_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_SOURCE_2D</source>
            <translation>mesh_hypo_source_face.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_SOURCE_3D</source>
            <translation>mesh_hypo_source_3d.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SEGMENT_LENGTH_AROUND_VERTEX</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_START_END_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SELECT</source>
            <translation>select1.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_CompositeSegment_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Hexa_3D</source>
            <translation>mesh_tree_algo_hexa.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_MEFISTO_2D</source>
            <translation>mesh_tree_algo_mefisto.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Prism_3D</source>
            <translation>mesh_tree_algo_projection_3d.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Projection_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Projection_2D</source>
            <translation>mesh_tree_algo_projection_2d.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Projection_3D</source>
            <translation>mesh_tree_hypo_projection_3d.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Quadrangle_2D</source>
            <translation>mesh_tree_algo_quad.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_RadialPrism_3D</source>
            <translation>mesh_tree_algo_radial_prism.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Regular_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_SegmentAroundVertex_0D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Arithmetic1D</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_AutomaticLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Deflection1D</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_LayerDistribution</source>
            <translation>mesh_tree_hypo_layers_distribution.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_LengthFromEdges</source>
            <translation>mesh_tree_hypo_area.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_LocalLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_MaxElementArea</source>
            <translation>mesh_tree_hypo_area.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_MaxElementVolume</source>
            <translation>mesh_tree_hypo_volume.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_NotConformAllowed</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_NumberOfLayers</source>
            <translation>mesh_tree_hypo_layers_distribution.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_NumberOfSegments</source>
            <translation>mesh_tree_hypo_segment.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ProjectionSource1D</source>
            <translation>mesh_tree_hypo_source_edge.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ProjectionSource2D</source>
            <translation>mesh_tree_hypo_source_face.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ProjectionSource3D</source>
            <translation>mesh_tree_hypo_source_3d_shape.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Propagation</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_QuadranglePreference</source>
            <translation>mesh_tree_algo_quad.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_QuadraticMesh</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_SegmentLengthAroundVertex</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_StartEndLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
    </context>
</TS>
