<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>StdMeshersGUI_StdHypothesisCreator</name>
    <message>
      <source>TO_IGNORE_EDGES_OR_NOT</source>
      <translation>指定したエッジが</translation>
    </message>
    <message>
      <source>NOT_TO_IGNORE_EDGES</source>
      <translation>エッジ層 （壁）</translation>
    </message>
    <message>
      <source>TO_IGNORE_EDGES</source>
      <translation>エッジ層 (入り江および oulets) なし</translation>
    </message>
    <message>
      <source>TO_IGNORE_FACES_OR_NOT</source>
      <translation>具体的に明記された面は</translation>
    </message>
    <message>
      <source>NOT_TO_IGNORE_FACES</source>
      <translation>レイヤ（壁）を伴う面</translation>
    </message>
    <message>
      <source>TO_IGNORE_FACES</source>
      <translation>レイヤ（入出口）を伴わない面</translation>
    </message>
    <message>
      <source>BAD_FACES_WARNING</source>
      <translation>明示された面はメッシュ/サブメッシュ形状のサブ形状ではありません。このメッシュ/サブメッシュのためにこれを使用する代わりにもう一つのhypothesisを作成していることが考えられます。</translation>
    </message>
    <message>
      <source>BAD_EDGES_WARNING</source>
      <translation>明示されたエッジはメッシュ/サブメッシュ形状のサブ形状ではありません。このメッシュ/サブメッシュのためにこれを使用する代わりにもう一つのhypothesisを作成していることが考えられます。</translation>
    </message>
    <message>
      <source>EXTMETH_SURF_OFFSET_SMOOTH</source>
      <translation>表面オフセットと平滑化</translation>
    </message>
    <message>
      <source>EXTRUSION_METHOD</source>
      <translation>押出方法</translation>
    </message>
    <message>
      <source>EXTMETH_NODE_OFFSET</source>
      <translation>節点オフセット</translation>
    </message>
    <message>
      <source>EXTMETH_FACE_OFFSET</source>
      <translation>面オフセット</translation>
    </message>
  </context>
  <context>
    <name>@default</name>
    <message>
      <source>SMESH_ARITHMETIC_1D_HYPOTHESIS</source>
      <translation>算術 1 d</translation>
    </message>
    <message>
      <source>SMESH_ARITHMETIC_1D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_GEOMETRIC_1D_HYPOTHESIS</source>
      <translation>ジオメトリの進行</translation>
    </message>
    <message>
      <source>SMESH_GEOMETRIC_1D_TITLE</source>
      <translation>仮定の構築</translation>
    </message>
    <message>
      <source>SMESH_COMMON_RATIO</source>
      <translation>標準比</translation>
    </message>
    <message>
      <source>SMESH_AUTOMATIC_LENGTH_HYPOTHESIS</source>
      <translation>自動の長さ</translation>
    </message>
    <message>
      <source>SMESH_AUTOMATIC_LENGTH_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_CONV_MODE</source>
      <translation>変換モード</translation>
    </message>
    <message>
      <source>SMESH_CUT_NEG_MODE</source>
      <translation>負のセクション</translation>
    </message>
    <message>
      <source>SMESH_ADAPTIVE1D_HYPOTHESIS</source>
      <translation>アダプティブ1次元Hypothesis</translation>
    </message>
    <message>
      <source>SMESH_MIN_SIZE</source>
      <translation>最小サイズ</translation>
    </message>
    <message>
      <source>SMESH_MAX_SIZE</source>
      <translation>最大サイズ</translation>
    </message>
    <message>
      <source>SMESH_ADAPTIVE1D_TITLE</source>
      <translation>Hypothesis構造</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_HYPOTHESIS</source>
      <translation>変形 d</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_PARAM</source>
      <translation>たわみ</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_DENSITY_FUNC</source>
      <translation>密度関数</translation>
    </message>
    <message>
      <source>SMESH_DISTR</source>
      <translation>配布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_EXPR</source>
      <translation>分析の密度分布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_REGULAR</source>
      <translation>等距離の分布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_SCALE</source>
      <translation>幾何学的進行</translation>
    </message>
    <message>
      <source>SMESH_DISTR_TAB</source>
      <translation>密度のテーブル</translation>
    </message>
    <message>
      <source>SMESH_DISTR_TYPE</source>
      <translation>分布の種類</translation>
    </message>
    <message>
      <source>SMESH_END_LENGTH_PARAM</source>
      <translation>最終的な長さ</translation>
    </message>
    <message>
      <source>SMESH_EXPR_FUNC</source>
      <translation>密度の表現</translation>
    </message>
    <message>
      <source>SMESH_EXP_MODE</source>
      <translation>出展者</translation>
    </message>
    <message>
      <source>SMESH_FINENESS_PARAM</source>
      <translation>細かさ</translation>
    </message>
    <message>
      <source>SMESH_FUNC_DOMAIN</source>
      <translation>警告: 関数 [0.1] のセグメントを定義しなければなりません</translation>
    </message>
    <message>
      <source>SMESH_INSERT_ROW</source>
      <translation>行を挿入します。</translation>
    </message>
    <message>
      <source>SMESH_INVALID_FUNCTION</source>
      <translation>関数が無効です。</translation>
    </message>
    <message>
      <source>SMESH_LAYERS_DISTRIBUTION</source>
      <translation>仮説 1 d</translation>
    </message>
    <message>
      <source>SMESH_LAYER_DISTRIBUTION_HYPOTHESIS</source>
      <translation>レイヤーの分布</translation>
    </message>
    <message>
      <source>SMESH_LAYER_DISTRIBUTION_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_HYPOTHESIS</source>
      <translation>平均の長さ</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_PARAM</source>
      <translation>長さ</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_PRECISION</source>
      <translation>精度</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS_1D_HYPOTHESIS</source>
      <translation>固定ポイント 1 d</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS_1D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_MAX_LENGTH_HYPOTHESIS</source>
      <translation>最大要素長</translation>
    </message>
    <message>
      <source>SMESH_CARTESIAN_PARAMS_HYPOTHESIS</source>
      <translation>体の継ぎ手パラメーター</translation>
    </message>
    <message>
      <source>SMESH_USE_PREESTIMATED_LENGTH</source>
      <translation>予測長さの使用</translation>
    </message>
    <message>
      <source>SMESH_VISCOUS_LAYERS_HYPOTHESIS</source>
      <translation>境界層設定</translation>
    </message>
    <message>
      <source>SMESH_VISCOUS_LAYERS_TITLE</source>
      <translation>詳細設定</translation>
    </message>
    <message>
      <source>SMESH_TOTAL_THICKNESS</source>
      <translation>総厚</translation>
    </message>
    <message>
      <source>SMESH_STRETCH_FACTOR</source>
      <translation>スケール ファクター</translation>
    </message>
    <message>
      <source>SMESH_FACES_WO_LAYERS</source>
      <translation>境界層 (入力と出力) のない顔</translation>
    </message>
    <message>
      <source>SMESH_EDGES_WO_LAYERS</source>
      <translation>エッジ境界層 (入力と出力) なし</translation>
    </message>
    <message>
      <source>SMESH_FACES_WITH_LAYERS</source>
      <translation>面層 （壁）</translation>
    </message>
    <message>
      <source>SMESH_EDGES_WITH_LAYERS</source>
      <translation>レイヤーのエッジ</translation>
    </message>
    <message>
      <source>SMESH_MAX_LENGTH_TITLE</source>
      <translation>要素長設定</translation>
    </message>
    <message>
      <source>SMESH_CARTESIAN_PARAMS_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_HYPOTHESIS</source>
      <translation>メッシュの最大範囲</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_PARAM</source>
      <translation>最大範囲</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_HYPOTHESIS</source>
      <translation>最大ボリューム メッシュの</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_PARAM</source>
      <translation>最大ボリューム</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_TITLE</source>
      <translation>詳細設定</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_HYPOTHESIS</source>
      <translation>セグメントの数</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_PARAM</source>
      <translation>セグメントの数</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_SCALE_PARAM</source>
      <translation>スケール ファクター</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_NO_CONV</source>
      <translation>変換なし</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS</source>
      <translation>層数</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_HYPOTHESIS</source>
      <translation>放射状のプリズムのパラメーター</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_2D_HYPOTHESIS</source>
      <translation>放射状の中庭のパラメーター</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_2D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_1D_HYPOTHESIS</source>
      <translation>1D 射影のソース</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_1D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_2D_HYPOTHESIS</source>
      <translation>2 D 投影用のソース</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_2D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_3D_HYPOTHESIS</source>
      <translation>ソースの 3 D プロジェクション</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_3D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_1D_HYPOTHESIS</source>
      <translation>エッジのソース</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_1D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_2D_HYPOTHESIS</source>
      <translation>顔のソース</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_2D_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_REMOVE_ROW</source>
      <translation>行を削除</translation>
    </message>
    <message>
      <source>SMESH_REVERSED_EDGES</source>
      <translation>逆端</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS</source>
      <translation>固定点</translation>
    </message>
    <message>
      <source>SMESH_RANGE</source>
      <translation>間隔</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS</source>
      <translation>Nb に登録セグメント</translation>
    </message>
    <message>
      <source>SMESH_SAME_NB_SEGMENTS</source>
      <translation>各間隔で同じ nb に登録セグメント</translation>
    </message>
    <message>
      <source>SMESH_BASE_VERTEX</source>
      <translation>基準点</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_HYPOTHESIS</source>
      <translation>点をセグメントの長さ</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_PARAM</source>
      <translation>長さ</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_3DSHAPE</source>
      <translation>3D オブジェクト</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_EDGE</source>
      <translation>Edge</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_EDGES</source>
      <translation>エッジのグループ</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_FACE</source>
      <translation>Face</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_FACES</source>
      <translation>面のグループ</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_MESH</source>
      <translation>メッシュ</translation>
    </message>
    <message>
      <source>SMESH_COPY_MESH</source>
      <translation>メッシュをコピーします。</translation>
    </message>
    <message>
      <source>SMESH_TO_COPY_GROUPS</source>
      <translation>グループのコピー</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX</source>
      <translation>ポイントのソース</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX1</source>
      <translation>ポイント ソース 1</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX2</source>
      <translation>ポイント ソース 2</translation>
    </message>
    <message>
      <source>SMESH_START_END_LENGTH_HYPOTHESIS</source>
      <translation>開始し、終了のローカルの長さ</translation>
    </message>
    <message>
      <source>SMESH_START_END_LENGTH_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_START_LENGTH_PARAM</source>
      <translation>初期の長さ</translation>
    </message>
    <message>
      <source>SMESH_TAB_FUNC</source>
      <translation>テーブル値関数の</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX</source>
      <translation>ターゲット ポイント</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX1</source>
      <translation>ポイント対象 1</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX2</source>
      <translation>ポイント対象 2</translation>
    </message>
    <message>
      <source>SMESH_QUADRANGLE_PARAMS_HYPOTHESIS</source>
      <translation>四角形のメッシュをパラメーター</translation>
    </message>
    <message>
      <source>SMESH_QUADRANGLE_PARAMS_TITLE</source>
      <translation>仮定の構成</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE</source>
      <translation>タイプ</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_QuadrangleParamWdg</name>
    <message>
      <source>SMESH_QUAD_TYPE_0</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_1</source>
      <translation>特権を持つ三角形</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_2</source>
      <translation>特権の中庭</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_3</source>
      <translation>特権の中庭 (反転)</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_4</source>
      <translation>削減</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_QuadrangleParamCreator</name>
    <message>
      <source>POINTS</source>
      <translation>点</translation>
    </message>
    <message>
      <source>SHAPES</source>
      <translation>頂点</translation>
    </message>
    <message>
      <source>TRANSITION</source>
      <translation>推移</translation>
    </message>
    <message>
      <source>ENF_NODES</source>
      <translation>強化された節点</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_LayerDistributionParamWdg</name>
    <message>
      <source>CHANGE_TYPE</source>
      <translation>種類の変更</translation>
    </message>
    <message>
      <source>CREATE</source>
      <translation>作成</translation>
    </message>
    <message>
      <source>EDIT</source>
      <translation>編集</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_CartesianParamCreator</name>
    <message>
      <source>THRESHOLD</source>
      <translation>しきい値</translation>
    </message>
    <message>
      <source>ADD_EDGES</source>
      <translation>エッジの実行</translation>
    </message>
    <message>
      <source>AXIS_X</source>
      <translation>X 軸</translation>
    </message>
    <message>
      <source>AXIS_Y</source>
      <translation>Y 軸</translation>
    </message>
    <message>
      <source>AXIS_Z</source>
      <translation>Z 軸</translation>
    </message>
    <message>
      <source>INVALID_AXES_DIR</source>
      <translation>無効な軸方向</translation>
    </message>
    <message>
      <source>FIXED_POINT</source>
      <translation>固定点</translation>
    </message>
    <message>
      <source>AXES_DIRECTION</source>
      <translation>軸方向</translation>
    </message>
    <message>
      <source>ORTHOGONAL_AXES</source>
      <translation>直交軸</translation>
    </message>
    <message>
      <source>OPTIMAL_AXES</source>
      <translation>最適軸</translation>
    </message>
    <message>
      <source>RESET_AXES</source>
      <translation>軸のリセット</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI::GridAxisTab</name>
    <message>
      <source>GRID_DEF_MODE</source>
      <translation>定義モード</translation>
    </message>
    <message>
      <source>SPACING</source>
      <translation>間隔</translation>
    </message>
    <message>
      <source>INSERT</source>
      <translation>挿入</translation>
    </message>
    <message>
      <source>COORD_STEP</source>
      <translation>ステップ</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_PropagationHelperWdg</name>
    <message>
      <source>HELPER</source>
      <translation>ヘルパ</translation>
    </message>
    <message>
      <source>SHOW_GEOMETRY</source>
      <translation>ジオメトリ全体の表示</translation>
    </message>
    <message>
      <source>PROPAGATION_CHAINS</source>
      <translation>伝播チェーン</translation>
    </message>
    <message>
      <source>ADD</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>REVERSE</source>
      <translation>反転</translation>
    </message>
    <message>
      <source>NO_CHAINS</source>
      <translation>(no chains)</translation>
    </message>
    <message>
      <source>CHAIN_NUM_NB_EDGES</source>
      <translation>Chain %1 (%2 edges)</translation>
    </message>
  </context>
</TS>
