<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>SMESH_ARITHMETIC_1D_HYPOTHESIS</source>
      <translation>算数 1 D</translation>
    </message>
    <message>
      <source>SMESH_ARITHMETIC_1D_PARAM</source>
      <translation>算術の理由</translation>
    </message>
    <message>
      <source>SMESH_ARITHMETIC_1D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_AUTOMATIC_LENGTH_HYPOTHESIS</source>
      <translation>長さの自動調整</translation>
    </message>
    <message>
      <source>SMESH_AUTOMATIC_LENGTH_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_CONV_MODE</source>
      <translation>変換モード</translation>
    </message>
    <message>
      <source>SMESH_CUT_NEG_MODE</source>
      <translation>否定的なカットします。</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_HYPOTHESIS</source>
      <translation>たわみ 1 D</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_PARAM</source>
      <translation>たわみ</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_DENSITY_FUNC</source>
      <translation>密度関数</translation>
    </message>
    <message>
      <source>SMESH_DISTR</source>
      <translation>配布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_EXPR</source>
      <translation>ピエゾ密度分布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_REGULAR</source>
      <translation>等距離の分布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_SCALE</source>
      <translation>規模の分布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_TAB</source>
      <translation>テーブルの密度分布</translation>
    </message>
    <message>
      <source>SMESH_DISTR_TYPE</source>
      <translation>分布の種類</translation>
    </message>
    <message>
      <source>SMESH_END_LENGTH_PARAM</source>
      <translation>最後の長さ</translation>
    </message>
    <message>
      <source>SMESH_EXPR_FUNC</source>
      <translation>密度関数</translation>
    </message>
    <message>
      <source>SMESH_EXP_MODE</source>
      <translation>指数</translation>
    </message>
    <message>
      <source>SMESH_FINENESS_PARAM</source>
      <translation>細かさ</translation>
    </message>
    <message>
      <source>SMESH_FUNC_DOMAIN</source>
      <translation>警告: 関数はセグメント [0..1] に定義する必要があります。</translation>
    </message>
    <message>
      <source>SMESH_INSERT_ROW</source>
      <translation>行を挿入します。</translation>
    </message>
    <message>
      <source>SMESH_INVALID_FUNCTION</source>
      <translation>関数が無効です。</translation>
    </message>
    <message>
      <source>SMESH_LAYERS_DISTRIBUTION</source>
      <translation>1 次元仮説</translation>
    </message>
    <message>
      <source>SMESH_LAYER_DISTRIBUTION_HYPOTHESIS</source>
      <translation>層の分布</translation>
    </message>
    <message>
      <source>SMESH_LAYER_DISTRIBUTION_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_HYPOTHESIS</source>
      <translation>ローカルの長さ</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_PARAM</source>
      <translation>長さ</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_PRECISION</source>
      <translation>精度</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS_1D_HYPOTHESIS</source>
      <translation>固定ポイント 1 D</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS_1D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_MAX_LENGTH_HYPOTHESIS</source>
      <translation>最大長</translation>
    </message>
    <message>
      <source>SMESH_CARTESIAN_PARAMS_HYPOTHESIS</source>
      <translation>体継ぎ手パラメーター</translation>
    </message>
    <message>
      <source>SMESH_USE_PREESTIMATED_LENGTH</source>
      <translation>伴う長さを使用します。</translation>
    </message>
    <message>
      <source>SMESH_VISCOUS_LAYERS_HYPOTHESIS</source>
      <translation>粘性層</translation>
    </message>
    <message>
      <source>SMESH_VISCOUS_LAYERS_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_TOTAL_THICKNESS</source>
      <translation>総厚</translation>
    </message>
    <message>
      <source>SMESH_STRETCH_FACTOR</source>
      <translation>伸縮係数</translation>
    </message>
    <message>
      <source>SMESH_FACES_WO_LAYERS</source>
      <translation>顔にレイヤー （入り江と oulets）</translation>
    </message>
    <message>
      <source>SMESH_EDGES_WO_LAYERS</source>
      <translation>エッジ層 （入り江と oulets） が不要</translation>
    </message>
    <message>
      <source>SMESH_MAX_LENGTH_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_CARTESIAN_PARAMS_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_HYPOTHESIS</source>
      <translation>最大。要素エリア</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_PARAM</source>
      <translation>最大。エリア</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_HYPOTHESIS</source>
      <translation>最大。要素音量</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_PARAM</source>
      <translation>最大。ボリューム</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_HYPOTHESIS</source>
      <translation>セグメントの数</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_PARAM</source>
      <translation>セグメントの数</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_SCALE_PARAM</source>
      <translation>尺度係数</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_NO_CONV</source>
      <translation>変換なし</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS</source>
      <translation>層の数</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_HYPOTHESIS</source>
      <translation>ラジアル プリズム パラメーター</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_2D_HYPOTHESIS</source>
      <translation>放射状の四角形パラメーター</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_2D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_1D_HYPOTHESIS</source>
      <translation>投射の源 1 D</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_1D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_2D_HYPOTHESIS</source>
      <translation>投影ソース 2 D</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_2D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_3D_HYPOTHESIS</source>
      <translation>投影ソースの 3 D</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_3D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_1D_HYPOTHESIS</source>
      <translation>ソース エッジ</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_1D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_2D_HYPOTHESIS</source>
      <translation>ソース顔</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_2D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_REMOVE_ROW</source>
      <translation>行を削除します。</translation>
    </message>
    <message>
      <source>SMESH_REVERSED_EDGES</source>
      <translation>逆のエッジ</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS</source>
      <translation>固定ポイント</translation>
    </message>
    <message>
      <source>SMESH_RANGE</source>
      <translation>範囲</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS</source>
      <translation>注意セグメント</translation>
    </message>
    <message>
      <source>SMESH_SAME_NB_SEGMENTS</source>
      <translation>同じ注意セグメントすべての間隔</translation>
    </message>
    <message>
      <source>SMESH_BASE_VERTEX</source>
      <translation>ベース頂点</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_HYPOTHESIS</source>
      <translation>頂点の周りのセグメントの長さ</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_PARAM</source>
      <translation>長さ</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_3DSHAPE</source>
      <translation>元の 3 D 図形</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_EDGE</source>
      <translation>ソース エッジ</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_EDGES</source>
      <translation>エッジのグループ</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_FACE</source>
      <translation>ソース顔</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_FACES</source>
      <translation>面のグループ</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_MESH</source>
      <translation>ソース メッシュ</translation>
    </message>
    <message>
      <source>SMESH_COPY_MESH</source>
      <translation>メッシュをコピーするには</translation>
    </message>
    <message>
      <source>SMESH_TO_COPY_GROUPS</source>
      <translation>グループをコピーするには</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX</source>
      <translation>ソース頂点</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX1</source>
      <translation>ソース頂点 1</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX2</source>
      <translation>ソース頂点 2</translation>
    </message>
    <message>
      <source>SMESH_START_END_LENGTH_HYPOTHESIS</source>
      <translation>開始と終了ローカルの長さ</translation>
    </message>
    <message>
      <source>SMESH_START_END_LENGTH_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_START_LENGTH_PARAM</source>
      <translation>長さを開始します。</translation>
    </message>
    <message>
      <source>SMESH_TAB_FUNC</source>
      <translation>テーブル関数</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX</source>
      <translation>ターゲットの頂点</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX1</source>
      <translation>ターゲット頂点 1</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX2</source>
      <translation>ターゲット頂点 2</translation>
    </message>
    <message>
      <source>SMESH_QUADRANGLE_PARAMS_HYPOTHESIS</source>
      <translation>四角形のパラメーター</translation>
    </message>
    <message>
      <source>SMESH_QUADRANGLE_PARAMS_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE</source>
      <translation>タイプ</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_QuadrangleParamWdg</name>
    <message>
      <source>SMESH_QUAD_TYPE_0</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_1</source>
      <translation>三角形の好み</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_2</source>
      <translation>四角形の設定</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_3</source>
      <translation>（逆に） の四角形の設定</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_4</source>
      <translation>削減</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_LayerDistributionParamWdg</name>
    <message>
      <source>CHANGE_TYPE</source>
      <translation>種類の変更</translation>
    </message>
    <message>
      <source>CREATE</source>
      <translation>作成します。</translation>
    </message>
    <message>
      <source>EDIT</source>
      <translation>編集</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_CartesianParamCreator</name>
    <message>
      <source>THRESHOLD</source>
      <translation>しきい値</translation>
    </message>
    <message>
      <source>AXIS_X</source>
      <translation>X 軸</translation>
    </message>
    <message>
      <source>AXIS_Y</source>
      <translation>Y 軸</translation>
    </message>
    <message>
      <source>AXIS_Z</source>
      <translation>軸、Z 軸</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI::GridAxisTab</name>
    <message>
      <source>GRID_DEF_MODE</source>
      <translation>定義モード</translation>
    </message>
    <message>
      <source>SPACING</source>
      <translation>間隔</translation>
    </message>
    <message>
      <source>INSERT</source>
      <translation>挿入</translation>
    </message>
    <message>
      <source>COORD_STEP</source>
      <translation>ステップ</translation>
    </message>
  </context>
</TS>
