<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
    <context>
        <name>@default</name>
        <message>
            <source>ICON_DLG_ARITHMETIC_1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GEOMETRIC_1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FIXED_POINTS_1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_AUTOMATIC_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_DEFLECTION1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ADAPTIVE1D</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LAYER_DISTRIBUTION</source>
            <translation>mesh_hypo_layer_distribution.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LOCAL_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MAX_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CARTESIAN_PARAMS</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_VISCOUS_LAYERS</source>
            <translation>mesh_hypo_viscous_layers.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MAX_ELEMENT_AREA</source>
            <translation>mesh_hypo_area.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MAX_ELEMENT_VOLUME</source>
            <translation>mesh_hypo_volume.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NB_SEGMENTS</source>
            <translation>mesh_hypo_segment.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NUMBER_OF_LAYERS</source>
            <translation>mesh_hypo_layer_distribution.png</translation>
        </message>
	<message>
            <source>ICON_DLG_NUMBER_OF_LAYERS_2D</source>
            <translation>mesh_hypo_layer_distribution.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_SOURCE_1D</source>
            <translation>mesh_hypo_source_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_SOURCE_2D</source>
            <translation>mesh_hypo_source_face.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_SOURCE_3D</source>
            <translation>mesh_hypo_source_3d.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRANGLE_PARAMS</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_IMPORT_SOURCE_1D</source>
            <translation>mesh_hypo_source_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_IMPORT_SOURCE_2D</source>
            <translation>mesh_hypo_source_face.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SEGMENT_LENGTH_AROUND_VERTEX</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_DLG_START_END_LENGTH</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SELECT</source>
            <translation>select1.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_CompositeSegment_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
	<message>
            <source>ICON_SMESH_TREE_ALGO_UseExisting_2D</source>
            <translation>mesh_tree_algo_existing_2D.png</translation>
        </message>
	<message>
            <source>ICON_SMESH_TREE_ALGO_UseExisting_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Hexa_3D</source>
            <translation>mesh_tree_algo_hexa.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_MEFISTO_2D</source>
            <translation>mesh_tree_algo_mefisto.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_PolygonPerFace_2D</source>
            <translation>mesh_tree_algo_polygon.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Projection_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Projection_2D</source>
            <translation>mesh_tree_algo_projection_2d.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Projection_3D</source>
            <translation>mesh_tree_hypo_projection_3d.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Quadrangle_2D</source>
            <translation>mesh_tree_algo_quad.png</translation>
        </message>
	<message>
            <source>ICON_SMESH_TREE_ALGO_RadialQuadrangle_1D2D</source>
            <translation>mesh_tree_algo_radial_quadrangle_1D2D.png</translation>
        </message>
	<message>
            <source>ICON_SMESH_TREE_ALGO_QuadFromMedialAxis_1D2D</source>
            <translation>mesh_tree_algo_quad.png</translation>
        </message>
	<message>
            <source>ICON_SMESH_TREE_ALGO_Prism_3D</source>
            <translation>mesh_tree_algo_prism.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_RadialPrism_3D</source>
            <translation>mesh_tree_algo_radial_prism.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_Regular_1D</source>
            <translation>mesh_tree_algo_regular.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO_SegmentAroundVertex_0D</source>
            <translation>mesh_tree_algo_0D.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Arithmetic1D</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Geometric1D</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_AutomaticLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Deflection1D</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Adaptive1D</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_LayerDistribution</source>
            <translation>mesh_tree_hypo_layers_distribution.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_LengthFromEdges</source>
            <translation>mesh_tree_hypo_area.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_LocalLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_MaxLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_MaxElementArea</source>
            <translation>mesh_tree_hypo_area.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_MaxElementVolume</source>
            <translation>mesh_tree_hypo_volume.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_NotConformAllowed</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_NumberOfLayers</source>
            <translation>mesh_tree_hypo_layers_distribution.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_NumberOfSegments</source>
            <translation>mesh_tree_hypo_segment.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ViscousLayers</source>
            <translation>mesh_tree_hypo_viscous_layers.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ProjectionSource1D</source>
            <translation>mesh_tree_hypo_source_edge.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ProjectionSource2D</source>
            <translation>mesh_tree_hypo_source_face.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_ProjectionSource3D</source>
            <translation>mesh_tree_hypo_source_3d_shape.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_Propagation</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_PropagOfDistribution</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_QuadranglePreference</source>
            <translation>mesh_tree_algo_quad.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_TrianglePreference</source>
            <translation>mesh_tree_algo_mefisto.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_QuadraticMesh</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_SegmentLengthAroundVertex</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO_StartEndLength</source>
            <translation>mesh_tree_hypo_length.png</translation>
        </message>
    </context>
    <context>
        <name>StdMeshersGUI_QuadrangleParamWdg</name>
        <message>
            <source>ICON_StdMeshers_Quadrangle_Params_0</source>
            <translation>mesh_quadrangle_standard.png</translation>
        </message>
        <message>
            <source>ICON_StdMeshers_Quadrangle_Params_1</source>
            <translation>mesh_quadrangle_triapref.png</translation>
        </message>
        <message>
            <source>ICON_StdMeshers_Quadrangle_Params_2</source>
            <translation>mesh_quadrangle_quadpref.png</translation>
        </message>
        <message>
            <source>ICON_StdMeshers_Quadrangle_Params_3</source>
            <translation>mesh_quadrangle_quadpref_reversed.png</translation>
        </message>
        <message>
            <source>ICON_StdMeshers_Quadrangle_Params_4</source>
            <translation>mesh_quadrangle_reduced.png</translation>
        </message>
    </context>
    <context>
    <name>StdMeshersGUI_StdHypothesisCreator</name>
        <message>
            <source>ICON_EXTMETH_SURF_OFFSET_SMOOTH</source>
            <translation>mesh_extmeth_surf_offset_smooth.png</translation>
        </message>
        <message>
            <source>ICON_EXTMETH_NODE_OFFSET</source>
            <translation>mesh_extmeth_node_offset.png</translation>
        </message>
        <message>
            <source>ICON_EXTMETH_FACE_OFFSET</source>
            <translation>mesh_extmeth_face_offset.png</translation>
        </message>
    </context>
</TS>
