#!/bin/sh
# Copyright (C) 2011-2012  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

# This script emulates the launcher script that will be generated by
# the padder SALOME component and give as the "job file" to the SALOME
# launcher to execute the padder job.
# The script is supposed to be executed where the data are located.

here=$(dirname $0)

# >>> This part should be written by the component
binpath=$here/padder.exe
envpath=$here/envPadder.sh
# <<<

. $envpath
$binpath $here/data.txt
