#!/bin/sh
# This script emulates the launcher script that will be generated by
# the padder SALOME component and give as the "job file" to the SALOME
# launcher to execute the padder job.
# The script is supposed to be executed where the data are located.

here=$(dirname $0)

# >>> This part should be written by the component
binpath=$here/padder.exe
envpath=$here/envPadder.sh
# <<<

. $envpath
$binpath $here/data.txt
