<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr_FR">
    <context>
        <name>@default</name>
        <message>
            <source>ICON_ADV_INFO</source>
            <translation>advanced_mesh_info.png</translation>
        </message>
        <message>
            <source>ICON_ANGLE</source>
            <translation>mesh_angle.png</translation>
        </message>
        <message>
            <source>ICON_APPEND</source>
            <translation>mesh_add.png</translation>
        </message>
        <message>
            <source>ICON_AREA</source>
            <translation>mesh_area.png</translation>
        </message>
        <message>
            <source>ICON_ASPECT</source>
            <translation>mesh_aspect.png</translation>
        </message>
        <message>
            <source>ICON_ASPECT_3D</source>
            <translation>mesh_aspect_3d.png</translation>
        </message>
        <message>
            <source>ICON_BUILD_COMPOUND</source>
            <translation>mesh_build_compound.png</translation>
        </message>
        <message>
            <source>ICON_COPY_MESH</source>
            <translation>copy_mesh.png</translation>
        </message>
        <message>
            <source>ICON_COMPUTE</source>
            <translation>mesh_compute.png</translation>
        </message>
        <message>
            <source>ICON_EVALUATE</source>
            <translation>mesh_evaluate.png</translation>
        </message>
        <message>
            <source>ICON_MESH_ORDER</source>
            <translation>mesh_order.png</translation>
        </message>
        <message>
            <source>ICON_PRECOMPUTE</source>
            <translation>mesh_precompute.png</translation>
        </message>
        <message>
            <source>ICON_CONNECTION</source>
            <translation>mesh_multi_edges.png</translation>
        </message>
        <message>
            <source>ICON_CONNECTION_2D</source>
            <translation>mesh_multi_edges_2d.png</translation>
        </message>
        <message>
            <source>ICON_CREATE_GROUP</source>
            <translation>mesh_group.png</translation>
        </message>
        <message>
            <source>ICON_CONSTRUCT_GROUP</source>
            <translation>mesh_make_group.png</translation>
        </message>
        <message>
            <source>ICON_CREATE_GEO_GROUP</source>
            <translation>mesh_groups_from_gemetry.png</translation>
        </message>
        <message>
            <source>ICON_CONV_TO_QUAD</source>
            <translation>mesh_conv_to_quad.png</translation>
        </message>
        <message>
            <source>ICON_CUT</source>
            <translation>mesh_cutGroups.png</translation>
        </message>
        <message>
            <source>ICON_CUTQUAD</source>
            <translation>mesh_cutquad.png</translation>
        </message>
        <message>
            <source>ICON_DELETE</source>
            <translation>delete.png</translation>
        </message>
        <message>
            <source>ICON_DEL_GROUP</source>
            <translation>mesh_deleteGroups.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ADD_SUBMESH</source>
            <translation>mesh_add_sub.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_COMPOUND_MESH</source>
            <translation>mesh_build_compound.png</translation>
        </message>
        <message>
            <source>ICON_DLG_COPY_MESH</source>
            <translation>copy_mesh.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BALL</source>
            <translation>mesh_ball.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BALL_ELEMENT</source>
            <translation>mesh_ball.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ELEM0D</source>
            <translation>mesh_0D_elem.png</translation>
        </message>
        <message>
            <source>ICON_0D_ON_ALL_NODES</source>
            <translation>mesh_0D_on_all_nodes.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EDGE</source>
            <translation>mesh_line.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EDIT_MESH</source>
            <translation>mesh_edit.png</translation>
        </message>
        <message>
            <source>ICON_DLG_HEXAS</source>
            <translation>mesh_hexa.png</translation>
        </message>
        <message>
            <source>ICON_DLG_INIT_MESH</source>
            <translation>mesh_init.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MERGE_ELEMENTS</source>
            <translation>mesh_merge_elements.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_DIAGONAL</source>
            <translation>mesh_diagonal.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_ORIENTATION</source>
            <translation>mesh_orientation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_ROTATION</source>
            <translation>mesh_rotation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_THROU_POINT</source>
            <translation>mesh_node_to_point.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MOVE_NODE</source>
            <translation>mesh_move_node.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MOVE_WITHOUT_NODE</source>
            <translation>mesh_move_without_node.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NODE</source>
            <translation>mesh_vertex.png</translation>
        </message>
        <message>
            <source>ICON_DLG_OCTA</source>
            <translation>mesh_octahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PENTA</source>
            <translation>mesh_pentahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POLYGON</source>
            <translation>mesh_polygon.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POLYHEDRON</source>
            <translation>mesh_polyhedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PYRAMID</source>
            <translation>mesh_pyramid.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRANGLE</source>
            <translation>mesh_quad.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_EDGE</source>
            <translation>mesh_quad_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_HEXAHEDRON</source>
            <translation>mesh_quad_hexahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRIQUADRATIC_HEXAHEDRON</source>
            <translation>mesh_triquad_hexahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_PENTAHEDRON</source>
            <translation>mesh_quad_pentahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_PYRAMID</source>
            <translation>mesh_quad_pyramid.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_QUADRANGLE</source>
            <translation>mesh_quad_quadrangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BIQUADRATIC_QUADRANGLE</source>
            <translation>mesh_biquad_quadrangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_POLYGON</source>
            <translation>mesh_quad_polygon.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_TETRAHEDRON</source>
            <translation>mesh_quad_tetrahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_TRIANGLE</source>
            <translation>mesh_quad_triangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BIQUADRATIC_TRIANGLE</source>
            <translation>mesh_biquad_triangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REM_ELEMENT</source>
            <translation>mesh_rem_element.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REM_NODE</source>
            <translation>mesh_rem_node.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REM_ORPHAN_NODES</source>
            <translation>mesh_rem_orphan_nodes.png</translation>
        </message>
        <message>
            <source>ICON_DLG_RENUMBERING_ELEMENTS</source>
            <translation>mesh_renumbering_elements.png</translation>
        </message>
        <message>
            <source>ICON_DLG_RENUMBERING_NODES</source>
            <translation>mesh_renumbering_nodes.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SMOOTHING</source>
            <translation>mesh_smoothing.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TETRAS</source>
            <translation>mesh_tetra.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRIANGLE</source>
            <translation>mesh_triangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHOOSE</source>
            <translation>mesh_choose.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHOOSE_ALL</source>
            <translation>mesh_choose_all.png</translation>
        </message>
        <message>
            <source>ICON_EDIT_GROUP</source>
            <translation>mesh_edit_group.png</translation>
        </message>
        <message>
            <source>ICON_EXTRUSION</source>
            <translation>mesh_extrusion.png</translation>
        </message>
        <message>
            <source>ICON_EXTRUSION_ALONG</source>
            <translation>mesh_extrusionpath.png</translation>
        </message>
        <message>
            <source>ICON_FILE_OPEN</source>
            <translation>open.png</translation>
        </message>
        <message>
            <source>ICON_FREE_EDGE</source>
            <translation>mesh_free_edges.png</translation>
        </message>
        <message>
            <source>ICON_FREE_EDGE_2D</source>
            <translation>mesh_free_edges_2d.png</translation>
        </message>
        <message>
            <source>ICON_FREE_NODE</source>
            <translation>mesh_free_nodes.png</translation>
        </message>
        <message>
            <source>ICON_FREE_FACES</source>
            <translation>mesh_free_faces.png</translation>
        </message>
        <message>
            <source>ICON_FIND_ELEM</source>
            <translation>mesh_find_elem_by_point.png</translation>
        </message>
        <message>
            <source>ICON_HYPO</source>
            <translation>mesh_hypo_length.png</translation>
        </message>
        <message>
            <source>ICON_HYPO_EDIT</source>
            <translation>mesh_hypo_edit.png</translation>
        </message>
        <message>
            <source>ICON_PLUS</source>
            <translation>mesh_plus.png</translation>
        </message>
        <message>
            <source>ICON_MINUS</source>
            <translation>mesh_minus.png</translation>
        </message>
        <message>
            <source>ICON_INTERSECT</source>
            <translation>mesh_intersectGroups.png</translation>
        </message>
        <message>
            <source>ICON_LENGTH</source>
            <translation>mesh_length.png</translation>
        </message>
        <message>
            <source>ICON_LENGTH_2D</source>
            <translation>mesh_length_2d.png</translation>
        </message>
        <message>
            <source>ICON_MAP</source>
            <translation>mesh_pattern.png</translation>
        </message>
        <message>
            <source>ICON_MAX_ELEMENT_LENGTH_2D</source>
            <translation>mesh_max_element_length_2d.png</translation>
        </message>
        <message>
            <source>ICON_MAX_ELEMENT_LENGTH_3D</source>
            <translation>mesh_max_element_length_3d.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_SMESH</source>
            <translation>mesh.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_2d</source>
            <translation>mesh_algo_mefisto.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_3d</source>
            <translation>mesh_algo_hexa.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_SAMPLE_2D</source>
            <translation>pattern_sample_2d.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_SAMPLE_3D</source>
            <translation>pattern_sample_3D.png</translation>
        </message>
        <message>
            <source>ICON_POINTS</source>
            <translation>mesh_points.png</translation>
        </message>
        <message>
            <source>ICON_REMOVE</source>
            <translation>mesh_remove.png</translation>
        </message>
        <message>
            <source>ICON_REVOLUTION</source>
            <translation>mesh_revolution.png</translation>
        </message>
        <message>
            <source>ICON_SELECT</source>
            <translation>select1.png</translation>
        </message>
        <message>
            <source>ICON_SHADE</source>
            <translation>mesh_shading.png</translation>
        </message>
        <message>
            <source>ICON_SHRINK</source>
            <translation>mesh_shrink.png</translation>
        </message>
        <message>
            <source>ICON_SKEW</source>
            <translation>mesh_skew.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_MERGE_NODES</source>
            <translation>mesh_merge_nodes.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_BORDERTOSIDE</source>
            <translation>mesh_sew_bordertoside.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_CONFORM_FREEBORDERS</source>
            <translation>mesh_sew_conform_freeborders.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_FREEBORDERS</source>
            <translation>mesh_sew_freeborders.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_SIDEELEMENTS</source>
            <translation>mesh_sew_sideelements.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SYMMETRY_AXIS</source>
            <translation>mesh_symmetry_axis.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SYMMETRY_PLANE</source>
            <translation>mesh_symmetry_plane.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SYMMETRY_POINT</source>
            <translation>mesh_symmetry_point.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TRANSLATION_POINTS</source>
            <translation>mesh_translation_points.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TRANSLATION_VECTOR</source>
            <translation>mesh_translation_vector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_SCALE</source>
            <translation>scale.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SCALE_ALONG_AXES</source>
            <translation>scale_along_axes.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REORIENT2D_POINT</source>
            <translation>reorient_faces_point.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REORIENT2D_FACE</source>
            <translation>reorient_faces_face.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REORIENT2D_VOLUME</source>
            <translation>reorient_faces_volume.png</translation>
        </message>
        <message>
            <source>ICON_REORIENT_2D</source>
            <translation>reorient_faces_face.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_DUPLICATE_NODES</source>
            <translation>mesh_duplicate_nodes.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_DUPLICATE_NODES_WITH_ELEM</source>
            <translation>mesh_duplicate_nodes_with_elem.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_DUPLICATE_ELEM_ONLY</source>
            <translation>mesh_duplicate_elem_only.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_DUPLICATE_GROUP_BOUNDARY</source>
            <translation>mesh_duplicate_group_boundary.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO</source>
            <translation>mesh_tree_algo.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_GROUP</source>
            <translation>mesh_tree_group.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_GROUP_ON_FILTER</source>
            <translation>mesh_tree_group_on_filter.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO</source>
            <translation>mesh_tree_hypo.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH</source>
            <translation>mesh_tree_mesh.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH_IMPORTED</source>
            <translation>mesh_tree_importedmesh.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH_PARTIAL</source>
            <translation>mesh_tree_mesh_partial.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH_WARN</source>
            <translation>mesh_tree_mesh_warn.png</translation>
        </message>
        <message>
            <source>ICON_STD_INFO</source>
            <translation>standard_mesh_info.png</translation>
        </message>
        <message>
            <source>ICON_TAPER</source>
            <translation>mesh_taper.png</translation>
        </message>
        <message>
            <source>ICON_UNION</source>
            <translation>mesh_unionGroups.png</translation>
        </message>
        <message>
            <source>ICON_UNION2TRI</source>
            <translation>mesh_union2tri.png</translation>
        </message>
        <message>
            <source>ICON_UNIONTRI</source>
            <translation>mesh_uniontri.png</translation>
        </message>
        <message>
            <source>ICON_UPDATE</source>
            <translation>mesh_update.png</translation>
        </message>
        <message>
            <source>ICON_VOLUME_3D</source>
            <translation>mesh_volume_3d.png</translation>
        </message>
        <message>
            <source>ICON_BARE_BORDER_VOLUME</source>
            <translation>bare_border_volume.png</translation>
        </message>
        <message>
            <source>ICON_BARE_BORDER_FACE</source>
            <translation>bare_border_face.png</translation>
        </message>
        <message>
            <source>ICON_OVER_CONSTRAINED_VOLUME</source>
            <translation>over_constrained_volume.png</translation>
        </message>
        <message>
            <source>ICON_OVER_CONSTRAINED_FACE</source>
            <translation>over_constrained_face.png</translation>
        </message>
        <message>
            <source>ICON_EQUAL_NODE</source>
            <translation>mesh_equal_node.png</translation>
        </message>
        <message>
            <source>ICON_EQUAL_EDGE</source>
            <translation>mesh_equal_edge.png</translation>
        </message>
        <message>
            <source>ICON_EQUAL_FACE</source>
            <translation>mesh_equal_face.png</translation>
        </message>
        <message>
            <source>ICON_EQUAL_VOLUME</source>
            <translation>mesh_equal_volume.png</translation>
        </message>
        <message>
            <source>ICON_WARP</source>
            <translation>mesh_wrap.png</translation>
        </message>
        <message>
            <source>ICON_WHAT_IS</source>
            <translation>mesh_elem_info.png</translation>
        </message>
        <message>
            <source>ICON_WIRE</source>
            <translation>mesh_wireframe.png</translation>
        </message>
        <message>
            <source>ICON_CLEAR_MESH</source>
            <translation>mesh_clear.png</translation>
        </message>
        <message>
            <source>ICON_UNDERLYING_ELEMS</source>
            <translation>mesh_extractGroup.png</translation>
        </message>
        <message>
            <source>ICON_2D_FROM_3D</source>
            <translation>mesh_2d_from_3d.png</translation>
        </message>
        <message>
            <source>ICON_SPLIT_TO_TETRA</source>
            <translation>split_into_tetra.png</translation>
        </message>
        <message>
            <source>ICON_SPLIT_BIQUAD</source>
            <translation>split_biquad.png</translation>
        </message>
	<message>
            <source>ICON_MEASURE_LENGTH</source>
            <translation>mesh_measure_length.png</translation>
        </message>
        <message>
            <source>ICON_MEASURE_AREA</source>
            <translation>mesh_measure_area.png</translation>
        </message>	
        <message>
            <source>ICON_MEASURE_VOLUME</source>
            <translation>mesh_measure_volume.png</translation>
        </message>
        <message>
            <source>ICON_MEASURE_BASIC_PROPS</source>
            <translation>mesh_measure_basic_props.png</translation>
        </message>
        <message>
            <source>ICON_MEASURE_MIN_DIST</source>
            <translation>mesh_min_dist.png</translation>
        </message>
        <message>
            <source>ICON_MEASURE_BND_BOX</source>
            <translation>mesh_bounding_box.png</translation>
        </message>
    </context>
</TS>
