<!DOCTYPE TS>
<TS version="1.1" >
    <context>
        <name>@default</name>
        <message>
            <source>ICON_APPEND</source>
            <translation>mesh_add.png</translation>
        </message>
	<message>
            <source>ICON_CREATE_GROUP</source>
            <translation>mesh_group.png</translation>
        </message>
        <message>
            <source>ICON_CONSTRUCT_GROUP</source>
            <translation>mesh_make_group.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ADD_SUBMESH</source>
            <translation>mesh_add_sub.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EDGE</source>
            <translation>mesh_line.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EDIT_MESH</source>
            <translation>mesh_edit.png</translation>
        </message>
        <message>
            <source>ICON_DLG_HEXAS</source>
            <translation>mesh_hexa.png</translation>
        </message>
        <message>
            <source>ICON_DLG_INIT_MESH</source>
            <translation>mesh_init.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_DIAGONAL</source>
            <translation>mesh_diagonal.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_ORIENTATION</source>
            <translation>mesh_orientation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MESH_ROTATION</source>
            <translation>mesh_rotation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MOVE_NODE</source>
            <translation>mesh_move_node.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NODE</source>
            <translation>mesh_vertex.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRANGLE</source>
            <translation>mesh_quad.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_EDGE</source>
            <translation>mesh_quad_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_HEXAHEDRON</source>
            <translation>mesh_quad_hexahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_PENTAHEDRON</source>
            <translation>mesh_quad_pentahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_PYRAMID</source>
            <translation>mesh_quad_pyramid.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_QUADRANGLE</source>
            <translation>mesh_quad_quadrangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_TETRAHEDRON</source>
            <translation>mesh_quad_tetrahedron.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUADRATIC_TRIANGLE</source>
            <translation>mesh_quad_triangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REM_ELEMENT</source>
            <translation>mesh_rem_element.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REM_NODE</source>
            <translation>mesh_rem_node.png</translation>
        </message>
        <message>
            <source>ICON_DLG_RENUMBERING_ELEMENTS</source>
            <translation>mesh_renumbering_elements.png</translation>
        </message>
        <message>
            <source>ICON_DLG_RENUMBERING_NODES</source>
            <translation>mesh_renumbering_nodes.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SMOOTHING</source>
            <translation>mesh_smoothing.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TETRAS</source>
            <translation>mesh_tetra.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRIANGLE</source>
            <translation>mesh_triangle.png</translation>
        </message>
        <message>
            <source>ICON_EDIT_GROUP</source>
            <translation>mesh_edit_group.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_SMESH</source>
            <translation>mesh.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_2d</source>
            <translation>mesh_algo_mefisto.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_3d</source>
            <translation>mesh_algo_hexa.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_SAMPLE_2D</source>
            <translation>pattern_sample_2d.png</translation>
        </message>
        <message>
            <source>ICON_PATTERN_SAMPLE_3D</source>
            <translation>pattern_sample_3D.png</translation>
        </message>
        <message>
            <source>ICON_REMOVE</source>
            <translation>mesh_remove.png</translation>
        </message>
        <message>
            <source>ICON_SELECT</source>
            <translation>select1.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_MERGE_NODES</source>
            <translation>mesh_merge_nodes.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_BORDERTOSIDE</source>
            <translation>mesh_sew_bordertoside.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_CONFORM_FREEBORDERS</source>
            <translation>mesh_sew_conform_freeborders.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_FREEBORDERS</source>
            <translation>mesh_sew_freeborders.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SEWING_SIDEELEMENTS</source>
            <translation>mesh_sew_sideelements.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SYMMETRY_AXIS</source>
            <translation>mesh_symmetry_axis.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SYMMETRY_PLANE</source>
            <translation>mesh_symmetry_plane.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_SYMMETRY_POINT</source>
            <translation>mesh_symmetry_point.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TRANSLATION_POINTS</source>
            <translation>mesh_translation_points.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TRANSLATION_VECTOR</source>
            <translation>mesh_translation_vector.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_ALGO</source>
            <translation>mesh_tree_algo.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_GROUP</source>
            <translation>mesh_tree_group.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_HYPO</source>
            <translation>mesh_tree_hypo.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH</source>
            <translation>mesh_tree_mesh.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH_IMPORTED</source>
            <translation>mesh_tree_importedmesh.png</translation>
        </message>
        <message>
            <source>ICON_SMESH_TREE_MESH_WARN</source>
            <translation>mesh_tree_mesh_warn.png</translation>
        </message>
    </context>
</TS>
