// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _Handle_SMDSControl_BoundaryEdges_HeaderFile
#define _Handle_SMDSControl_BoundaryEdges_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_SMDSControl_MeshBoundary_HeaderFile
#include "Handle_SMDSControl_MeshBoundary.hxx"
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(SMDSControl_MeshBoundary);
class SMDSControl_BoundaryEdges;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(SMDSControl_BoundaryEdges);

class Handle(SMDSControl_BoundaryEdges) : public Handle(SMDSControl_MeshBoundary) {
  public:
    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
    Handle(SMDSControl_BoundaryEdges)():Handle(SMDSControl_MeshBoundary)() {} 
    Handle(SMDSControl_BoundaryEdges)(const Handle(SMDSControl_BoundaryEdges)& aHandle) : Handle(SMDSControl_MeshBoundary)(aHandle) 
     {
     }

    Handle(SMDSControl_BoundaryEdges)(const SMDSControl_BoundaryEdges* anItem) : Handle(SMDSControl_MeshBoundary)((SMDSControl_MeshBoundary *)anItem) 
     {
     }

    Handle(SMDSControl_BoundaryEdges)& operator=(const Handle(SMDSControl_BoundaryEdges)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(SMDSControl_BoundaryEdges)& operator=(const SMDSControl_BoundaryEdges* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    SMDSControl_BoundaryEdges* operator->() 
     {
      return (SMDSControl_BoundaryEdges *)ControlAccess();
     }

    SMDSControl_BoundaryEdges* operator->() const 
     {
      return (SMDSControl_BoundaryEdges *)ControlAccess();
     }

   Standard_EXPORT ~Handle(SMDSControl_BoundaryEdges)();
 
   Standard_EXPORT static const Handle(SMDSControl_BoundaryEdges) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
