// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _SMDS_ExtendedMap_HeaderFile
#define _SMDS_ExtendedMap_HeaderFile

#ifndef _TCollection_BasicMap_HeaderFile
#include <TCollection_BasicMap.hxx>
#endif
#ifndef _Handle_SMDS_MeshElement_HeaderFile
#include "Handle_SMDS_MeshElement.hxx"
#endif
#ifndef _Handle_SMDS_StdMapNodeOfExtendedMap_HeaderFile
#include "Handle_SMDS_StdMapNodeOfExtendedMap.hxx"
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_DomainError;
class SMDS_MeshElement;
class SMDS_MeshElementMapHasher;
class SMDS_StdMapNodeOfExtendedMap;
class SMDS_MapIteratorOfExtendedMap;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class SMDS_ExtendedMap  : public TCollection_BasicMap {

public:

    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
 // Methods PUBLIC
 // 
Standard_EXPORT SMDS_ExtendedMap(const Standard_Integer NbBuckets = 1);
Standard_EXPORT   SMDS_ExtendedMap& Assign(const SMDS_ExtendedMap& Other) ;
  SMDS_ExtendedMap& operator =(const SMDS_ExtendedMap& Other) 
{
  return Assign(Other);
}

Standard_EXPORT   void ReSize(const Standard_Integer NbBuckets) ;
Standard_EXPORT   void Clear() ;
~SMDS_ExtendedMap()
{
  Clear();
}

Standard_EXPORT   Standard_Boolean Add(const Handle(SMDS_MeshElement)& aKey) ;
Standard_EXPORT   Standard_Boolean Contains(const Handle(SMDS_MeshElement)& aKey) const;
Standard_EXPORT   Standard_Boolean Remove(const Handle(SMDS_MeshElement)& aKey) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 
Standard_EXPORT SMDS_ExtendedMap(const SMDS_ExtendedMap& Other);


 // Fields PRIVATE
 //


};





// other inline functions and methods (like "C++: function call" methods)
//


#endif
