// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _SMDS_MapOfMeshOrientedElement_HeaderFile
#define _SMDS_MapOfMeshOrientedElement_HeaderFile

#ifndef _SMDS_ExtendedOrientedMap_HeaderFile
#include "SMDS_ExtendedOrientedMap.hxx"
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_SMDS_MeshElement_HeaderFile
#include "Handle_SMDS_MeshElement.hxx"
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class SMDS_MeshElement;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class SMDS_MapOfMeshOrientedElement  : public SMDS_ExtendedOrientedMap {

public:

    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
 // Methods PUBLIC
 // 
Standard_EXPORT inline SMDS_MapOfMeshOrientedElement(const Standard_Integer NbBuckets = 1);
Standard_EXPORT  const Handle_SMDS_MeshElement& Find(const Handle(SMDS_MeshElement)& K) const;
 const Handle_SMDS_MeshElement& operator()(const Handle(SMDS_MeshElement)& K) const
{
  return Find(K);
}

Standard_EXPORT   Handle_SMDS_MeshElement& ChangeFind(const Handle(SMDS_MeshElement)& K) ;
  Handle_SMDS_MeshElement& operator()(const Handle(SMDS_MeshElement)& K) 
{
  return ChangeFind(K);
}

Standard_EXPORT  const Handle_SMDS_MeshElement& FindID(const Standard_Integer ID) const;
 const Handle_SMDS_MeshElement& operator()(const Standard_Integer ID) const
{
  return FindID(ID);
}

Standard_EXPORT   Standard_Boolean ContainsID(const Standard_Integer ID) const;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};


#include "SMDS_MapOfMeshOrientedElement.lxx"



// other inline functions and methods (like "C++: function call" methods)
//


#endif
