using namespace std;
// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#include "SMDS_ListIteratorOfListOfMeshElement.hxx"

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _SMDS_ListOfMeshElement_HeaderFile
#include "SMDS_ListOfMeshElement.hxx"
#endif
#ifndef _SMDS_MeshElement_HeaderFile
#include "SMDS_MeshElement.hxx"
#endif
#ifndef _SMDS_ListNodeOfListOfMeshElement_HeaderFile
#include "SMDS_ListNodeOfListOfMeshElement.hxx"
#endif
 

#define Item Handle_SMDS_MeshElement
#define Item_hxx <SMDS_MeshElement.hxx>
#define TCollection_ListNode SMDS_ListNodeOfListOfMeshElement
#define TCollection_ListNode_hxx <SMDS_ListNodeOfListOfMeshElement.hxx>
#define TCollection_ListIterator SMDS_ListIteratorOfListOfMeshElement
#define TCollection_ListIterator_hxx <SMDS_ListIteratorOfListOfMeshElement.hxx>
#define Handle_TCollection_ListNode Handle_SMDS_ListNodeOfListOfMeshElement
#define TCollection_ListNode_Type_() SMDS_ListNodeOfListOfMeshElement_Type_()
#define TCollection_List SMDS_ListOfMeshElement
#define TCollection_List_hxx <SMDS_ListOfMeshElement.hxx>
#include <TCollection_ListIterator.gxx>

