// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _SMDS_ListIteratorOfListOfMeshElement_HeaderFile
#define _SMDS_ListIteratorOfListOfMeshElement_HeaderFile

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_SMDS_MeshElement_HeaderFile
#include "Handle_SMDS_MeshElement.hxx"
#endif
#ifndef _Handle_SMDS_ListNodeOfListOfMeshElement_HeaderFile
#include "Handle_SMDS_ListNodeOfListOfMeshElement.hxx"
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class SMDS_ListOfMeshElement;
class SMDS_MeshElement;
class SMDS_ListNodeOfListOfMeshElement;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class SMDS_ListIteratorOfListOfMeshElement  {

public:

    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
 // Methods PUBLIC
 // 
Standard_EXPORT SMDS_ListIteratorOfListOfMeshElement();
Standard_EXPORT SMDS_ListIteratorOfListOfMeshElement(const SMDS_ListOfMeshElement& L);
Standard_EXPORT   void Initialize(const SMDS_ListOfMeshElement& L) ;
Standard_EXPORT inline   Standard_Boolean More() const;
Standard_EXPORT   void Next() ;
Standard_EXPORT   Handle_SMDS_MeshElement& Value() const;


friend class SMDS_ListOfMeshElement;



protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Standard_Address current;
Standard_Address previous;


};

#define Item Handle_SMDS_MeshElement
#define Item_hxx <SMDS_MeshElement.hxx>
#define TCollection_ListNode SMDS_ListNodeOfListOfMeshElement
#define TCollection_ListNode_hxx <SMDS_ListNodeOfListOfMeshElement.hxx>
#define TCollection_ListIterator SMDS_ListIteratorOfListOfMeshElement
#define TCollection_ListIterator_hxx <SMDS_ListIteratorOfListOfMeshElement.hxx>
#define Handle_TCollection_ListNode Handle_SMDS_ListNodeOfListOfMeshElement
#define TCollection_ListNode_Type_() SMDS_ListNodeOfListOfMeshElement_Type_()
#define TCollection_List SMDS_ListOfMeshElement
#define TCollection_List_hxx <SMDS_ListOfMeshElement.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other inline functions and methods (like "C++: function call" methods)
//


#endif
