// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _SMDS_DataMapOfPntInteger_HeaderFile
#define _SMDS_DataMapOfPntInteger_HeaderFile

#ifndef _TCollection_BasicMap_HeaderFile
#include <TCollection_BasicMap.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_SMDS_DataMapNodeOfDataMapOfPntInteger_HeaderFile
#include "Handle_SMDS_DataMapNodeOfDataMapOfPntInteger.hxx"
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_DomainError;
class Standard_NoSuchObject;
class gp_Pnt;
class SMDS_PntHasher;
class SMDS_DataMapNodeOfDataMapOfPntInteger;
class SMDS_DataMapIteratorOfDataMapOfPntInteger;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class SMDS_DataMapOfPntInteger  : public TCollection_BasicMap {

public:

    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
 // Methods PUBLIC
 // 
Standard_EXPORT SMDS_DataMapOfPntInteger(const Standard_Integer NbBuckets = 1);
Standard_EXPORT   SMDS_DataMapOfPntInteger& Assign(const SMDS_DataMapOfPntInteger& Other) ;
  SMDS_DataMapOfPntInteger& operator =(const SMDS_DataMapOfPntInteger& Other) 
{
  return Assign(Other);
}

Standard_EXPORT   void ReSize(const Standard_Integer NbBuckets) ;
Standard_EXPORT   void Clear() ;
~SMDS_DataMapOfPntInteger()
{
  Clear();
}

Standard_EXPORT   Standard_Boolean Bind(const gp_Pnt& K,const Standard_Integer& I) ;
Standard_EXPORT   Standard_Boolean IsBound(const gp_Pnt& K) const;
Standard_EXPORT   Standard_Boolean UnBind(const gp_Pnt& K) ;
Standard_EXPORT  const Standard_Integer& Find(const gp_Pnt& K) const;
 const Standard_Integer& operator()(const gp_Pnt& K) const
{
  return Find(K);
}

Standard_EXPORT   Standard_Integer& ChangeFind(const gp_Pnt& K) ;
  Standard_Integer& operator()(const gp_Pnt& K) 
{
  return ChangeFind(K);
}






protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 
Standard_EXPORT SMDS_DataMapOfPntInteger(const SMDS_DataMapOfPntInteger& Other);


 // Fields PRIVATE
 //


};





// other inline functions and methods (like "C++: function call" methods)
//


#endif
