using namespace std;
// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#include "SMDS_ListIteratorOfListOfMesh.hxx"

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _SMDS_ListOfMesh_HeaderFile
#include "SMDS_ListOfMesh.hxx"
#endif
#ifndef _SMDS_Mesh_HeaderFile
#include "SMDS_Mesh.hxx"
#endif
#ifndef _SMDS_ListNodeOfListOfMesh_HeaderFile
#include "SMDS_ListNodeOfListOfMesh.hxx"
#endif
 

#define Item Handle_SMDS_Mesh
#define Item_hxx <SMDS_Mesh.hxx>
#define TCollection_ListNode SMDS_ListNodeOfListOfMesh
#define TCollection_ListNode_hxx <SMDS_ListNodeOfListOfMesh.hxx>
#define TCollection_ListIterator SMDS_ListIteratorOfListOfMesh
#define TCollection_ListIterator_hxx <SMDS_ListIteratorOfListOfMesh.hxx>
#define Handle_TCollection_ListNode Handle_SMDS_ListNodeOfListOfMesh
#define TCollection_ListNode_Type_() SMDS_ListNodeOfListOfMesh_Type_()
#define TCollection_List SMDS_ListOfMesh
#define TCollection_List_hxx <SMDS_ListOfMesh.hxx>
#include <TCollection_ListIterator.gxx>

