// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _SMDSControl_BoundaryEdges_HeaderFile
#define _SMDSControl_BoundaryEdges_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_SMDSControl_BoundaryEdges_HeaderFile
#include "Handle_SMDSControl_BoundaryEdges.hxx"
#endif

#ifndef _SMDS_MapOfMeshElement_HeaderFile
#include "SMDS_MapOfMeshElement.hxx"
#endif
#ifndef _SMDSControl_MeshBoundary_HeaderFile
#include "SMDSControl_MeshBoundary.hxx"
#endif
#ifndef _Handle_SMDS_Mesh_HeaderFile
#include "Handle_SMDS_Mesh.hxx"
#endif
class SMDS_Mesh;


class SMDSControl_BoundaryEdges : public SMDSControl_MeshBoundary {

public:

    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
 // Methods PUBLIC
 // 
Standard_EXPORT SMDSControl_BoundaryEdges(const Handle(SMDS_Mesh)& M);
Standard_EXPORT virtual  void Compute() ;
Standard_EXPORT ~SMDSControl_BoundaryEdges();




 // Type management
 //
 Standard_EXPORT friend Handle_Standard_Type& SMDSControl_BoundaryEdges_Type_();
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
SMDS_MapOfMeshElement myBoundaryEdges;


};





// other inline functions and methods (like "C++: function call" methods)
//


#endif
