# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/scratch/I27518/V7_3_build/V7_3_0/modules/src/SMESH_V7_3_0p2/src/Tools/blocFissure/ihm/fissureCoude.ui'
#
# Created: Wed Mar  5 09:49:21 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(826, 540)
        self.gridLayout_8 = QtGui.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dsb_angle = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_angle.setDecimals(5)
        self.dsb_angle.setMinimum(-181.0)
        self.dsb_angle.setMaximum(180.0)
        self.dsb_angle.setProperty("value", -181.0)
        self.dsb_angle.setObjectName(_fromUtf8("dsb_angle"))
        self.gridLayout.addWidget(self.dsb_angle, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.dsb_epais = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_epais.setDecimals(5)
        self.dsb_epais.setMaximum(1000000.0)
        self.dsb_epais.setObjectName(_fromUtf8("dsb_epais"))
        self.gridLayout.addWidget(self.dsb_epais, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.dsb_lTubeP2 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_lTubeP2.setDecimals(5)
        self.dsb_lTubeP2.setMaximum(1000000.0)
        self.dsb_lTubeP2.setObjectName(_fromUtf8("dsb_lTubeP2"))
        self.gridLayout.addWidget(self.dsb_lTubeP2, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dsb_dext = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_dext.setDecimals(5)
        self.dsb_dext.setMaximum(1000000.0)
        self.dsb_dext.setObjectName(_fromUtf8("dsb_dext"))
        self.gridLayout.addWidget(self.dsb_dext, 5, 1, 1, 1)
        self.dsb_lTubeP1 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_lTubeP1.setDecimals(5)
        self.dsb_lTubeP1.setMaximum(1000000.0)
        self.dsb_lTubeP1.setObjectName(_fromUtf8("dsb_lTubeP1"))
        self.gridLayout.addWidget(self.dsb_lTubeP1, 2, 1, 1, 1)
        self.dsb_rCintr = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_rCintr.setDecimals(5)
        self.dsb_rCintr.setMaximum(1000000.0)
        self.dsb_rCintr.setObjectName(_fromUtf8("dsb_rCintr"))
        self.gridLayout.addWidget(self.dsb_rCintr, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.cb_optDiscrSain = QtGui.QCheckBox(Dialog)
        self.cb_optDiscrSain.setObjectName(_fromUtf8("cb_optDiscrSain"))
        self.verticalLayout_2.addWidget(self.cb_optDiscrSain)
        self.gb_discrSain = QtGui.QGroupBox(Dialog)
        self.gb_discrSain.setObjectName(_fromUtf8("gb_discrSain"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_discrSain)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.gb_discrSain)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.gb_discrSain)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.sb_nbAxeTubeP1 = QtGui.QSpinBox(self.gb_discrSain)
        self.sb_nbAxeTubeP1.setMaximum(10000)
        self.sb_nbAxeTubeP1.setProperty("value", 15)
        self.sb_nbAxeTubeP1.setObjectName(_fromUtf8("sb_nbAxeTubeP1"))
        self.gridLayout_3.addWidget(self.sb_nbAxeTubeP1, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gb_discrSain)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.sb_nbAxeTubeP2 = QtGui.QSpinBox(self.gb_discrSain)
        self.sb_nbAxeTubeP2.setMaximum(10000)
        self.sb_nbAxeTubeP2.setProperty("value", 15)
        self.sb_nbAxeTubeP2.setObjectName(_fromUtf8("sb_nbAxeTubeP2"))
        self.gridLayout_3.addWidget(self.sb_nbAxeTubeP2, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gb_discrSain)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.sb_nbAxeCoude = QtGui.QSpinBox(self.gb_discrSain)
        self.sb_nbAxeCoude.setMaximum(10000)
        self.sb_nbAxeCoude.setProperty("value", 10)
        self.sb_nbAxeCoude.setObjectName(_fromUtf8("sb_nbAxeCoude"))
        self.gridLayout_3.addWidget(self.sb_nbAxeCoude, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gb_discrSain)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.sb_nbCirconf = QtGui.QSpinBox(self.gb_discrSain)
        self.sb_nbCirconf.setMaximum(10000)
        self.sb_nbCirconf.setProperty("value", 20)
        self.sb_nbCirconf.setObjectName(_fromUtf8("sb_nbCirconf"))
        self.gridLayout_3.addWidget(self.sb_nbCirconf, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gb_discrSain)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.sb_nbEpaisseur = QtGui.QSpinBox(self.gb_discrSain)
        self.sb_nbEpaisseur.setMaximum(10000)
        self.sb_nbEpaisseur.setProperty("value", 3)
        self.sb_nbEpaisseur.setObjectName(_fromUtf8("sb_nbEpaisseur"))
        self.gridLayout_3.addWidget(self.sb_nbEpaisseur, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gb_discrSain)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.rb_fissInt = QtGui.QRadioButton(self.groupBox_4)
        self.rb_fissInt.setObjectName(_fromUtf8("rb_fissInt"))
        self.verticalLayout_7.addWidget(self.rb_fissInt)
        self.rb_fissExt = QtGui.QRadioButton(self.groupBox_4)
        self.rb_fissExt.setObjectName(_fromUtf8("rb_fissExt"))
        self.verticalLayout_7.addWidget(self.rb_fissExt)
        self.gridLayout_10.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 0, 1, 1, 1)
        self.cb_forceEllipse = QtGui.QCheckBox(self.groupBox_5)
        self.cb_forceEllipse.setAccessibleDescription(_fromUtf8(""))
        self.cb_forceEllipse.setObjectName(_fromUtf8("cb_forceEllipse"))
        self.gridLayout_10.addWidget(self.cb_forceEllipse, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 1, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.dsb_azimut = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsb_azimut.setDecimals(5)
        self.dsb_azimut.setMinimum(-181.0)
        self.dsb_azimut.setMaximum(180.0)
        self.dsb_azimut.setProperty("value", -181.0)
        self.dsb_azimut.setObjectName(_fromUtf8("dsb_azimut"))
        self.gridLayout_5.addWidget(self.dsb_azimut, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.dsb_profondeur = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsb_profondeur.setDecimals(5)
        self.dsb_profondeur.setMaximum(1000000.0)
        self.dsb_profondeur.setObjectName(_fromUtf8("dsb_profondeur"))
        self.gridLayout_5.addWidget(self.dsb_profondeur, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.dsb_orientation = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsb_orientation.setDecimals(5)
        self.dsb_orientation.setMinimum(-1.0)
        self.dsb_orientation.setMaximum(90.0)
        self.dsb_orientation.setProperty("value", -1.0)
        self.dsb_orientation.setObjectName(_fromUtf8("dsb_orientation"))
        self.gridLayout_5.addWidget(self.dsb_orientation, 3, 1, 1, 1)
        self.dsb_longueur = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsb_longueur.setDecimals(5)
        self.dsb_longueur.setMaximum(1000000.0)
        self.dsb_longueur.setObjectName(_fromUtf8("dsb_longueur"))
        self.gridLayout_5.addWidget(self.dsb_longueur, 1, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.rb_absCurv = QtGui.QRadioButton(self.groupBox_11)
        self.rb_absCurv.setObjectName(_fromUtf8("rb_absCurv"))
        self.gridLayout_11.addWidget(self.rb_absCurv, 0, 0, 1, 1)
        self.rb_posiAngul = QtGui.QRadioButton(self.groupBox_11)
        self.rb_posiAngul.setObjectName(_fromUtf8("rb_posiAngul"))
        self.gridLayout_11.addWidget(self.rb_posiAngul, 1, 0, 1, 1)
        self.dsb_absCurv = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.dsb_absCurv.setDecimals(5)
        self.dsb_absCurv.setMaximum(1000000.0)
        self.dsb_absCurv.setObjectName(_fromUtf8("dsb_absCurv"))
        self.gridLayout_11.addWidget(self.dsb_absCurv, 0, 1, 1, 1)
        self.dsb_posiAngul = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.dsb_posiAngul.setDecimals(5)
        self.dsb_posiAngul.setMinimum(-181.0)
        self.dsb_posiAngul.setMaximum(180.0)
        self.dsb_posiAngul.setProperty("value", -181.0)
        self.dsb_posiAngul.setObjectName(_fromUtf8("dsb_posiAngul"))
        self.gridLayout_11.addWidget(self.dsb_posiAngul, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_11, 2, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_21 = QtGui.QLabel(self.groupBox_9)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_9)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 1)
        self.sb_nbCouronne = QtGui.QSpinBox(self.groupBox_9)
        self.sb_nbCouronne.setMinimum(1)
        self.sb_nbCouronne.setMaximum(10000)
        self.sb_nbCouronne.setProperty("value", 1)
        self.sb_nbCouronne.setObjectName(_fromUtf8("sb_nbCouronne"))
        self.gridLayout_6.addWidget(self.sb_nbCouronne, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_9)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_6.addWidget(self.label_23, 3, 0, 1, 1)
        self.sb_nbSecteur = QtGui.QSpinBox(self.groupBox_9)
        self.sb_nbSecteur.setMinimum(3)
        self.sb_nbSecteur.setMaximum(10000)
        self.sb_nbSecteur.setProperty("value", 3)
        self.sb_nbSecteur.setObjectName(_fromUtf8("sb_nbSecteur"))
        self.gridLayout_6.addWidget(self.sb_nbSecteur, 3, 1, 1, 1)
        self.sb_nbTranches = QtGui.QSpinBox(self.groupBox_9)
        self.sb_nbTranches.setMinimum(7)
        self.sb_nbTranches.setMaximum(100000)
        self.sb_nbTranches.setProperty("value", 7)
        self.sb_nbTranches.setObjectName(_fromUtf8("sb_nbTranches"))
        self.gridLayout_6.addWidget(self.sb_nbTranches, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_9)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 4, 0, 1, 1)
        self.dsb_rayonTore = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.dsb_rayonTore.setEnabled(False)
        self.dsb_rayonTore.setDecimals(5)
        self.dsb_rayonTore.setMaximum(1000000.0)
        self.dsb_rayonTore.setProperty("value", 2.0)
        self.dsb_rayonTore.setObjectName(_fromUtf8("dsb_rayonTore"))
        self.gridLayout_6.addWidget(self.dsb_rayonTore, 4, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_6)
        spacerItem5 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.cb_optDiscrFiss = QtGui.QCheckBox(self.groupBox_8)
        self.cb_optDiscrFiss.setObjectName(_fromUtf8("cb_optDiscrFiss"))
        self.verticalLayout_5.addWidget(self.cb_optDiscrFiss)
        self.gb_discrFacesExternes = QtGui.QGroupBox(self.groupBox_8)
        self.gb_discrFacesExternes.setEnabled(True)
        self.gb_discrFacesExternes.setObjectName(_fromUtf8("gb_discrFacesExternes"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gb_discrFacesExternes)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_24 = QtGui.QLabel(self.gb_discrFacesExternes)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.dsb_aretesFaceFissure = QtGui.QDoubleSpinBox(self.gb_discrFacesExternes)
        self.dsb_aretesFaceFissure.setDecimals(5)
        self.dsb_aretesFaceFissure.setMaximum(1000000.0)
        self.dsb_aretesFaceFissure.setObjectName(_fromUtf8("dsb_aretesFaceFissure"))
        self.horizontalLayout_3.addWidget(self.dsb_aretesFaceFissure)
        spacerItem6 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.gb_discrFacesExternes)
        self.gridLayout_7.addWidget(self.groupBox_8, 1, 0, 1, 2)
        self.gb_zoneRemail = QtGui.QGroupBox(self.groupBox_6)
        self.gb_zoneRemail.setEnabled(True)
        self.gb_zoneRemail.setObjectName(_fromUtf8("gb_zoneRemail"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gb_zoneRemail)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.dsb_influence = QtGui.QDoubleSpinBox(self.gb_zoneRemail)
        self.dsb_influence.setDecimals(5)
        self.dsb_influence.setMaximum(1000000.0)
        self.dsb_influence.setObjectName(_fromUtf8("dsb_influence"))
        self.gridLayout_17.addWidget(self.dsb_influence, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gb_zoneRemail)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_17.addWidget(self.label_25, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(47, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gb_zoneRemail, 2, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.lb_calcul = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lb_calcul.setFont(font)
        self.lb_calcul.setObjectName(_fromUtf8("lb_calcul"))
        self.horizontalLayout_6.addWidget(self.lb_calcul)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem11, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pb_reset = QtGui.QPushButton(Dialog)
        self.pb_reset.setObjectName(_fromUtf8("pb_reset"))
        self.horizontalLayout.addWidget(self.pb_reset)
        self.pb_valPrec = QtGui.QPushButton(Dialog)
        self.pb_valPrec.setObjectName(_fromUtf8("pb_valPrec"))
        self.horizontalLayout.addWidget(self.pb_valPrec)
        self.pb_recharger = QtGui.QPushButton(Dialog)
        self.pb_recharger.setObjectName(_fromUtf8("pb_recharger"))
        self.horizontalLayout.addWidget(self.pb_recharger)
        self.pb_sauver = QtGui.QPushButton(Dialog)
        self.pb_sauver.setObjectName(_fromUtf8("pb_sauver"))
        self.horizontalLayout.addWidget(self.pb_sauver)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_8.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.cb_optDiscrSain, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.gb_discrSain.setShown)
        QtCore.QObject.connect(self.cb_optDiscrFiss, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.gb_discrFacesExternes.setShown)
        QtCore.QObject.connect(self.cb_optDiscrFiss, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.gb_zoneRemail.setShown)
        QtCore.QObject.connect(self.cb_optDiscrFiss, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.dsb_rayonTore.setEnabled)
        QtCore.QObject.connect(self.rb_absCurv, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dsb_absCurv.setEnabled)
        QtCore.QObject.connect(self.rb_posiAngul, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dsb_posiAngul.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Coude Sain", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Géométrie", None))
        self.label_3.setText(_translate("Dialog", "L_TUBE_P1", None))
        self.dsb_angle.setToolTip(_translate("Dialog", "Valeur de l\'angle du coude en degrés", None))
        self.label_2.setText(_translate("Dialog", "R_CINTR", None))
        self.label_5.setText(_translate("Dialog", "EPAIS", None))
        self.dsb_epais.setToolTip(_translate("Dialog", "Valeur de l’épaisseur du coude et des embouts", None))
        self.label_4.setText(_translate("Dialog", "L_TUBE_P2", None))
        self.dsb_lTubeP2.setToolTip(_translate("Dialog", "Valeur de la longueur de l’embout P2 à l’extrémité duquel seront appliqués les chargements", None))
        self.label_6.setText(_translate("Dialog", "DEXT", None))
        self.label.setText(_translate("Dialog", "ANGLE", None))
        self.dsb_dext.setToolTip(_translate("Dialog", "Valeur du diamètre externe du coude et des embouts droits", None))
        self.dsb_lTubeP1.setToolTip(_translate("Dialog", "Valeur de la longueur de l’embout P1 à l’extrémité duquel seront appliqués les chargements", None))
        self.dsb_rCintr.setToolTip(_translate("Dialog", "Valeur du rayon de cintrage du coude", None))
        self.cb_optDiscrSain.setToolTip(_translate("Dialog", "Paramètres optionnels de discretisation", None))
        self.cb_optDiscrSain.setText(_translate("Dialog", "Options de discretisation", None))
        self.gb_discrSain.setTitle(_translate("Dialog", "Maillage", None))
        self.label_7.setText(_translate("Dialog", "Nombres de segments", None))
        self.label_8.setText(_translate("Dialog", "NB_AXE_TUBE_P1", None))
        self.sb_nbAxeTubeP1.setToolTip(_translate("Dialog", "Nombre d’éléments le long de l’embout P1", None))
        self.label_9.setText(_translate("Dialog", "NB_AXE_TUBE_P2", None))
        self.sb_nbAxeTubeP2.setToolTip(_translate("Dialog", "Nombre d’éléments le long de l’embout P2", None))
        self.label_10.setText(_translate("Dialog", "NB_AXE_COUDE", None))
        self.sb_nbAxeCoude.setToolTip(_translate("Dialog", "Nombre d’éléments le long de l’axe du coude", None))
        self.label_11.setText(_translate("Dialog", "NB_CIRCONF", None))
        self.sb_nbCirconf.setToolTip(_translate("Dialog", "<html><head/><body><p>Nombre d’éléments le long de la circonférence</p><p>(nombre pair)</p></body></html>", None))
        self.label_13.setText(_translate("Dialog", "NB_EPAISSEUR", None))
        self.sb_nbEpaisseur.setToolTip(_translate("Dialog", "Nombre d\'éléments dans l\'épaisseur", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Fissure", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Géométrie fissure", None))
        self.groupBox_4.setTitle(_translate("Dialog", "position", None))
        self.rb_fissInt.setToolTip(_translate("Dialog", "<html><head/><body><p>Fissure positionnée sur la face interne</p></body></html>", None))
        self.rb_fissInt.setText(_translate("Dialog", "fissure interne", None))
        self.rb_fissExt.setToolTip(_translate("Dialog", "<html><head/><body><p>Fissure positionnée sur la face externe</p></body></html>", None))
        self.rb_fissExt.setText(_translate("Dialog", "fissure externe", None))
        self.cb_forceEllipse.setToolTip(_translate("Dialog", "<html><head/><body><p>Forcer une fissure de forme elliptique, même si elle est longue</p></body></html>", None))
        self.cb_forceEllipse.setText(_translate("Dialog", "forcer elliptique", None))
        self.dsb_azimut.setToolTip(_translate("Dialog", "Valeur de la position circonférentielle du centre de la fissure comptée positivement en degrés à partir de l’extrados jusqu’à l’intrados en passant par le flanc gauche", None))
        self.label_18.setText(_translate("Dialog", "PROFONDEUR", None))
        self.dsb_profondeur.setToolTip(_translate("Dialog", "<html><head/><body><p>Profondeur de la fissure :</p><p>distance maximale entre le fond de fissure et la peau interne ou externe sur laquelle débouche la fissure</p></body></html>", None))
        self.label_19.setText(_translate("Dialog", "LONGUEUR", None))
        self.label_14.setText(_translate("Dialog", "AZIMUT", None))
        self.label_15.setText(_translate("Dialog", "ORIEN", None))
        self.dsb_orientation.setToolTip(_translate("Dialog", "Valeur de l’angle en degrés formé par le grand axe de la fissure et la génératrice du coude donnant ainsi l’orientation du défaut", None))
        self.dsb_longueur.setToolTip(_translate("Dialog", "Longueur du grand axe de la fissure mesurée sur le coude en peau interne ou externe, suivant la peau sur laquelle se trouve la fissure", None))
        self.groupBox_11.setTitle(_translate("Dialog", "position longitudinale", None))
        self.rb_absCurv.setToolTip(_translate("Dialog", "Définition de la position longitudinale par une abscisse curiviligne", None))
        self.rb_absCurv.setText(_translate("Dialog", "ABS_CURV", None))
        self.rb_posiAngul.setToolTip(_translate("Dialog", "Définition de la position longitudinale par un angle", None))
        self.rb_posiAngul.setText(_translate("Dialog", "POSI_ANGUL", None))
        self.dsb_absCurv.setToolTip(_translate("Dialog", "<html><head/><body><p>Valeur de la position longitudinale du centre de la fissure définie par rapport à l\'interface de l\'embout P1 :</p><p>Abcisse curviligne le long de l\'axe du coude, sur la peau interne ou externe, selon la position de la fissure.</p><p><br/></p></body></html>", None))
        self.dsb_posiAngul.setToolTip(_translate("Dialog", "<html><head/><body><p>Valeur de la position longitudinale du centre de la fissure définie par rapport à l\'interface de l\'embout P1 :</p><p>Angle en degrés formé par la section contenant le centre de la fissure et l\'interface de l\'embout P1.</p><p><br/></p></body></html>", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Maillage fissure", None))
        self.groupBox_8.setTitle(_translate("Dialog", "maillage zone de fissure", None))
        self.groupBox_9.setTitle(_translate("Dialog", "pipe rayonnant", None))
        self.label_21.setText(_translate("Dialog", "NB_TRANCHES", None))
        self.label_22.setText(_translate("Dialog", "NB_COURONNE", None))
        self.sb_nbCouronne.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>nombre de couronnes du maillage rayonnant autour de la ligne de fond de fissure, y compris la couronne centrale formée de prismes.</p></body></html>", None))
        self.label_23.setText(_translate("Dialog", "NB_SECTEUR", None))
        self.sb_nbSecteur.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>nombre de secteurs selon un cercle normal au fond de fissure.</p></body></html>", None))
        self.sb_nbTranches.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>Nombre de mailles (approximatif) le long de la ligne de fond de fissure.</p></body></html>", None))
        self.label_20.setText(_translate("Dialog", "RAYON_TORE", None))
        self.dsb_rayonTore.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>Rayon du pipe.</p></body></html>", None))
        self.cb_optDiscrFiss.setToolTip(_translate("Dialog", "Paramètres optionnels de discrétisation", None))
        self.cb_optDiscrFiss.setText(_translate("Dialog", "Options de discretisation", None))
        self.gb_discrFacesExternes.setTitle(_translate("Dialog", "faces externes", None))
        self.label_24.setText(_translate("Dialog", "aretes face fissure", None))
        self.dsb_aretesFaceFissure.setToolTip(_translate("Dialog", "<html><head/><body><p>Faces externes de la zone à remailler.</p><p>Mailage en triangles : valeur cible des arêtes.</p></body></html>", None))
        self.gb_zoneRemail.setTitle(_translate("Dialog", "identification zone à remailler", None))
        self.dsb_influence.setToolTip(_translate("Dialog", "<html><head/><body><p>La zone remaillée contiendra toutes les mailles du maillage sain à une distance de la face de fissure inférieure à cette valeur.</p></body></html>", None))
        self.label_25.setText(_translate("Dialog", "distance influence", None))
        self.lb_calcul.setText(_translate("Dialog", "--- Calcul en cours ---", None))
        self.pb_reset.setToolTip(_translate("Dialog", "réinitialisation de tous les paramètres à leur valeur par défaut", None))
        self.pb_reset.setText(_translate("Dialog", "Reset", None))
        self.pb_valPrec.setToolTip(_translate("Dialog", "réinitialisation de tous les paramètres à leur valeur de la précédente éxécution", None))
        self.pb_valPrec.setText(_translate("Dialog", "Précédent", None))
        self.pb_recharger.setToolTip(_translate("Dialog", "réinitialisation des paramètres à partir d\'un fichier préalablement sauvegardé", None))
        self.pb_recharger.setText(_translate("Dialog", "Recharger", None))
        self.pb_sauver.setToolTip(_translate("Dialog", "sauvegarde des paramètres dans un fichier à choisir", None))
        self.pb_sauver.setText(_translate("Dialog", "Sauver", None))

