# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/scratch/I27518/V7_3_build/V7_3_0/modules/src/SMESH_V7_3_0p2/src/Tools/blocFissure/ihm/fissureGenerale.ui'
#
# Created: Wed Mar  5 09:49:21 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(631, 490)
        self.gridLayout_11 = QtGui.QGridLayout(Dialog)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pb_maillage = QtGui.QPushButton(self.groupBox)
        self.pb_maillage.setObjectName(_fromUtf8("pb_maillage"))
        self.gridLayout.addWidget(self.pb_maillage, 0, 0, 1, 1)
        self.le_maillage = QtGui.QLineEdit(self.groupBox)
        self.le_maillage.setObjectName(_fromUtf8("le_maillage"))
        self.gridLayout.addWidget(self.le_maillage, 0, 1, 1, 1)
        self.pb_facefiss = QtGui.QPushButton(self.groupBox)
        self.pb_facefiss.setObjectName(_fromUtf8("pb_facefiss"))
        self.gridLayout.addWidget(self.pb_facefiss, 1, 0, 1, 1)
        self.le_facefiss = QtGui.QLineEdit(self.groupBox)
        self.le_facefiss.setObjectName(_fromUtf8("le_facefiss"))
        self.gridLayout.addWidget(self.le_facefiss, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.le_fondfiss = QtGui.QLineEdit(self.groupBox)
        self.le_fondfiss.setObjectName(_fromUtf8("le_fondfiss"))
        self.horizontalLayout.addWidget(self.le_fondfiss)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 1, 2)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.dsb_influence = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_influence.setObjectName(_fromUtf8("dsb_influence"))
        self.gridLayout_6.addWidget(self.dsb_influence, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.dsb_meshBrepMin = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_meshBrepMin.setMaximum(1000000.0)
        self.dsb_meshBrepMin.setObjectName(_fromUtf8("dsb_meshBrepMin"))
        self.gridLayout_2.addWidget(self.dsb_meshBrepMin, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.dsb_meshBrepMax = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.dsb_meshBrepMax.setMaximum(1000000.0)
        self.dsb_meshBrepMax.setObjectName(_fromUtf8("dsb_meshBrepMax"))
        self.gridLayout_2.addWidget(self.dsb_meshBrepMax, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.dsb_rayonPipe = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsb_rayonPipe.setMaximum(1000000.0)
        self.dsb_rayonPipe.setObjectName(_fromUtf8("dsb_rayonPipe"))
        self.gridLayout_3.addWidget(self.dsb_rayonPipe, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.dsb_lenSegPipe = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsb_lenSegPipe.setMaximum(1000000.0)
        self.dsb_lenSegPipe.setObjectName(_fromUtf8("dsb_lenSegPipe"))
        self.gridLayout_3.addWidget(self.dsb_lenSegPipe, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.sb_couronnes = QtGui.QSpinBox(self.groupBox_5)
        self.sb_couronnes.setMinimum(2)
        self.sb_couronnes.setMaximum(10000)
        self.sb_couronnes.setProperty("value", 4)
        self.sb_couronnes.setObjectName(_fromUtf8("sb_couronnes"))
        self.gridLayout_3.addWidget(self.sb_couronnes, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.sb_secteurs = QtGui.QSpinBox(self.groupBox_5)
        self.sb_secteurs.setMinimum(4)
        self.sb_secteurs.setMaximum(10000)
        self.sb_secteurs.setProperty("value", 8)
        self.sb_secteurs.setObjectName(_fromUtf8("sb_secteurs"))
        self.gridLayout_3.addWidget(self.sb_secteurs, 3, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.dsb_areteFaceFissure = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.dsb_areteFaceFissure.setMaximum(1000000.0)
        self.dsb_areteFaceFissure.setObjectName(_fromUtf8("dsb_areteFaceFissure"))
        self.gridLayout_8.addWidget(self.dsb_areteFaceFissure, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 0, 1, 2, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 112, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 1, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem6, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.bb_OkCancel = QtGui.QDialogButtonBox(Dialog)
        self.bb_OkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.bb_OkCancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bb_OkCancel.setObjectName(_fromUtf8("bb_OkCancel"))
        self.horizontalLayout_5.addWidget(self.bb_OkCancel)
        self.gridLayout_11.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.bb_OkCancel, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.bb_OkCancel, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        Dialog.setToolTip(_translate("Dialog", "<html><head/><body><p>Insertion d\'un maillage de fissure dans un maillage hexaédrique sain.</p><p>Le maillage sain est fourni sous forme de fichier Med.</p><p>La face de fissure est décrite par une géométrie dans un fichier brep.</p><p>La ou les arêtes de fond de fissure sont données par leurs index dans la face de fissure.</p><p>La procédure identfie des mailles saines à enlever et remailler, construit un maillage régulier rayonnant autour de la ligne de fond de fissure, reconstitue les faces externes en triangles, complète la zone à remailler en tétraèdres.</p></body></html>", None))
        self.groupBox.setTitle(_translate("Dialog", "maillage sain et géometries de fissure", None))
        self.pb_maillage.setToolTip(_translate("Dialog", "<html><head/><body><p>sélection du fichier med du maillage sain (hexaèdres)</p></body></html>", None))
        self.pb_maillage.setText(_translate("Dialog", "maillage sain", None))
        self.le_maillage.setToolTip(_translate("Dialog", "<html><head/><body><p>fichier med du maillage sain (hexaèdres)</p></body></html>", None))
        self.pb_facefiss.setToolTip(_translate("Dialog", "<html><head/><body><p>sélection du fichier brep (géométrie) décrivant la face de fissure.</p></body></html>", None))
        self.pb_facefiss.setText(_translate("Dialog", "face fissure", None))
        self.le_facefiss.setToolTip(_translate("Dialog", "<html><head/><body><p>fichier brep (géométrie) décrivant la face de fissure.</p></body></html>", None))
        self.label.setText(_translate("Dialog", "index edges fond fissure", None))
        self.le_fondfiss.setToolTip(_translate("Dialog", "<html><head/><body><p>Index des edges décrivant le fond de fissure, dans la face de fissure.</p><p>Sous forme d\'une liste Python.</p><p>Exemples :<span style=\" color:#00ffff;\"/><span style=\" font-style:italic; color:#00ffff;\">[5,9]</span> ou <span style=\" font-style:italic; color:#00ffff;\">[3]</span></p><p>(on peut récupérer ces valeurs à l\'aide du dialogue de création de groupes d\'edges, dans GEOM)</p></body></html>", None))
        self.groupBox_2.setTitle(_translate("Dialog", "identification zone à remailler", None))
        self.label_2.setText(_translate("Dialog", "distance influence", None))
        self.dsb_influence.setToolTip(_translate("Dialog", "<html><head/><body><p>La zone remaillée contiendra toutes les mailles du maillage sain à une distance de la face de fissure inférieure à cette valeur.</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("Dialog", "prémaillage face fissure", None))
        self.label_3.setText(_translate("Dialog", "min", None))
        self.dsb_meshBrepMin.setToolTip(_translate("Dialog", "<html><head/><body><p>Pour faciliter la détermination de la zone à remailler, il faut des points sur la face de fissure, suffisament resserrés, en relation avec la taille des mailles du maillage sain.</p><p>Ces points sont obtenus par pré maillage de la face de fissure, en triangles. On donne la taille min et max des triangles.</p></body></html>", None))
        self.label_4.setText(_translate("Dialog", "max", None))
        self.dsb_meshBrepMax.setToolTip(_translate("Dialog", "<html><head/><body><p>Pour faciliter la détermination de la zone à remailler, il faut des points sur la face de fissure, suffisament resserrés, en relation avec la taille des mailles du maillage sain.</p><p>Ces points sont obtenus par pré maillage de la face de fissure, en triangles. On donne la taille min et max des triangles.</p></body></html>", None))
        self.groupBox_4.setTitle(_translate("Dialog", "maillage zone de fissure", None))
        self.groupBox_5.setTitle(_translate("Dialog", "pipe rayonnant", None))
        self.label_5.setText(_translate("Dialog", "rayon pipe", None))
        self.dsb_rayonPipe.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>Rayon du pipe.</p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "longueur mailles", None))
        self.dsb_lenSegPipe.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>Longueur des mailles le long de la ligne de fond de fissure.</p></body></html>", None))
        self.label_7.setText(_translate("Dialog", "couronnes", None))
        self.sb_couronnes.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>nombre de couronnes de mailles autour de la ligne de fond de fissure.</p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "secteurs", None))
        self.sb_secteurs.setToolTip(_translate("Dialog", "<html><head/><body><p>Pipe rayonnant construit sur le fond de fissure :</p><p>nombre de secteurs selon un cercle normal au fond de fissure.</p></body></html>", None))
        self.groupBox_6.setTitle(_translate("Dialog", "faces externes", None))
        self.label_9.setText(_translate("Dialog", "aretes face fissure", None))
        self.dsb_areteFaceFissure.setToolTip(_translate("Dialog", "<html><head/><body><p>Faces externes de la zone à remailler.</p><p>Mailage en triangles : valeur cible des arêtes.</p></body></html>", None))

